/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

/**
 * Service interface for ComplaintsEJB.
 */
public interface ComplaintsService {

   public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint> retrieveComplaints( java.lang.String doLaaCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint retrieveComplaint( int complaintId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint retrieveComplaint( java.lang.String doLaaCd,java.lang.String year,java.lang.String month )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint createComplaint( us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint complaint )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void modifyComplaint( us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint complaint )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void removeComplaint( us.oh.state.epa.stars2.database.dbObjects.ceta.Complaint complaint )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

}
