/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

import us.oh.state.epa.stars2.database.dbObjects.ValidationMessage;
import us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest;
import us.oh.state.epa.stars2.framework.exception.DAOException;

/**
 * Service interface for DelegationRequestEJB.
 */
public interface DelegationRequestService {

   public us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest createDelegationRequest( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest delegationRequest )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest modifyDelegationRequest( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest delegationRequest )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

   /**
    * Locate all of the delegation requests for a given facility.
    */
   public us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest[] retrieveDelegationRequests( java.lang.String facilityID )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Locate delecation request by app id
    */
   public us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest retrieveDelegationRequest( int applicationId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public boolean deleteDelegationRequest( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest delegationRequest )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

   public boolean submit( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest ret )
      throws java.rmi.RemoteException;

   /**
    * Create a new row in the appropriate Compliance Attachment table.
    */
   public us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment createDelegationAttachment( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest request,us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment attachment,java.io.InputStream fileStream )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

   public boolean modifyDelegationAttachment( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest request,us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment attachment )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Delete row in the DC_CORRESPONDENCE table.
    */
   public boolean deleteDelegationAttachment( us.oh.state.epa.stars2.database.dbObjects.application.DelegationRequest request,us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment attachment )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public ValidationMessage[] validateDelegationRequest(DelegationRequest delegationRequest)
			throws DAOException;
}
