/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

import java.io.InputStream;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Map;

import us.oh.state.epa.stars2.app.emissionsReport.UsEpaEisReport;
import us.oh.state.epa.stars2.database.dbObjects.document.TemplateDocument;
import us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef;
import us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport;
import us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod;
import us.oh.state.epa.stars2.database.dbObjects.emissionReport.PollutantPair;
import us.oh.state.epa.stars2.database.dbObjects.facility.Facility;
import us.oh.state.epa.stars2.framework.exception.ApplicationException;
import us.oh.state.epa.stars2.framework.exception.DAOException;
import us.oh.state.epa.stars2.framework.exception.ValidationException;
import us.oh.state.epa.stars2.webcommon.reports.EmissionCalcMethod;
import us.oh.state.epa.stars2.webcommon.reports.EmissionRow;
import us.oh.state.epa.stars2.webcommon.reports.MissingFIREFactor;
import us.oh.state.epa.stars2.webcommon.reports.ReportTemplates;
import us.wy.state.deq.impact.app.emissionsReport.EiDataImport;
import us.wy.state.deq.impact.app.emissionsReport.EiDataImportCriteria;
import us.wy.state.deq.impact.database.dbObjects.projectTracking.ProjectAttachment;
import us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment;
import us.oh.state.epa.stars2.database.dbObjects.complianceReport.ComplianceReport;
import us.oh.state.epa.stars2.database.dbObjects.complianceReport.ComplianceReportAttachment;;
/**
 * Service interface for EmissionsReportEJB.
 */
public interface EmissionsReportService {

	public void createSubmitReport(java.lang.String facilityId, int fpId,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport report,
			java.lang.Integer userId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.webcommon.reports.NtvReport createEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport report)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.webcommon.reports.NtvReport createEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport report,
			boolean calledFromSubmit,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport createEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport newReport)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void createEmissionsReport(
			java.lang.String county,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport newReport,
			boolean submitFromStaging,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport rpt,
			int minValue,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports2, boolean openedForEdit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow createFireRow(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow row)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public boolean modifyFireRow(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow row)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyEmissionsReportState(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.lang.String state)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyEmissionsReportState(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.lang.String state,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyEmissionsReportState(
			us.oh.state.epa.stars2.webcommon.reports.NtvReport rpt,
			java.lang.String state)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public boolean modifyEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportEU> reuClearList,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod pClear, boolean openedForEdit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyEmissionsPeriod(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod period, boolean openedForEdit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void saveContact(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.NTVContactType cType,
			boolean existing,
			us.oh.state.epa.stars2.database.dbObjects.infrastructure.Contact newContact)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void deleteEmissionsReport(
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void deleteEmissionsReport(
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void deleteEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void deleteEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	public void deleteEmissionsReport(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dao.Transaction trans, boolean removeFiles)
					throws us.oh.state.epa.stars2.framework.exception.DAOException,
					java.rmi.RemoteException;

	public void cancelEmissionsReport(java.lang.Integer externalId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportNote retrieveReportNote(
			int noteId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.facility.Facility editFacilityProfile(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility oldFacility,
			java.lang.Integer userId, boolean openedForEdit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void setFeeInfo(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.util.ArrayList<us.oh.state.epa.stars2.webcommon.reports.EmissionRow> emissions,
			us.oh.state.epa.stars2.database.dbObjects.serviceCatalog.SCEmissionsReport scFer)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	public void updateReportedEmissionsTotal(us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report, Float newTotal)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
	java.rmi.RemoteException;

	public void submitReportFromPortal(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.Task fromTask)
			throws java.rmi.RemoteException;

	public void submitReportFromPortal(
			us.oh.state.epa.stars2.database.dbObjects.Task fromTask)
			throws java.rmi.RemoteException;

	public boolean ntvSubmit(
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			java.lang.String state,
			int minValue,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports2,
			java.lang.Integer userId, boolean sourceIsStaging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.lang.Integer backupWorkFlow(java.lang.String facilityId,
			java.lang.Integer rptId, boolean viewOnly)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void submitReport(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			java.util.ArrayList<us.oh.state.epa.stars2.webcommon.reports.EmissionRow> emissions,
			us.oh.state.epa.stars2.database.dbObjects.serviceCatalog.SCEmissionsReport scFer,
			java.lang.Integer userId, boolean sourceIsStaging, boolean openedForEdit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void createTotalsRows(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.util.ArrayList<us.oh.state.epa.stars2.webcommon.reports.EmissionRow> emissions)
			throws java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsRptInfo getEmissionsRptInfo(
			java.lang.Integer year, java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void setEmissionsRptInfo(
			us.oh.state.epa.stars2.database.dao.EmissionsReportDAO emissionsRptDAO,
			java.lang.Integer year, java.lang.String facilityId,
			java.lang.String state)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void setEmissionsRptInfoReminder(
			java.lang.Integer yearOne,
			java.lang.Integer yearTwo,
			java.lang.String fullAddr,
			java.lang.String reportingTypeCd,
			java.lang.String toState,
			java.lang.String facilityId,
			java.lang.Integer fpId,
			us.oh.state.epa.stars2.database.dbObjects.document.Correspondence correspondence,
			java.lang.Integer userId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportNote[] retrieveReportNotes(
			java.lang.Integer reportId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionTotal[] retrieveEmissionTotals(
			java.lang.Integer reportId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.Emissions[] retrieveEmissions(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod periodId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport[] retrieveEmissionsReports(
			int fpId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.webcommon.reports.NtvReport retrieveNtvEmissionsReport(
			java.lang.Integer reportId, boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport retrieveLatestEmissionReport(
			java.lang.Integer year, java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport retrieveLatestTvEmissionReport(
			java.lang.Integer year, java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport retrieveLatestSubmittedEmissionReport(
			java.lang.Integer year, java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport retrieveEmissionsReportRow(
			java.lang.Integer reportId, boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport retrieveEmissionsReport(
			java.lang.Integer reportId, boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportSearch[] searchEmissionsReports(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportSearch searchObj,
			boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportSearch[] searchEmissionsReportForScore(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportSearch searchObj)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FacilityYearPair[] retrieveStragglerNTV(
			int oddYear, int evenYear)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.lang.Integer[] searchFacilities(
			java.util.List<java.lang.String> counties,
			java.lang.String doLaaCd, java.lang.String facilityId,
			int firstYear, int lastYear, boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsRptInfo> getYearlyReportingInfo(
			java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsRptInfo getCurrentReportingInfo(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility f)
			throws java.rmi.RemoteException;

	public void updateYearlyReportingInfo(
			java.lang.String facilityId,
			java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsRptInfo> info)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void updateYearlyReportingInfo(
			java.lang.String facilityId,
			java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsRptInfo> info,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void updateYearlyReportingToShutdown(java.lang.String facilityId,
			int year, us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	public int turnOnReporting(us.oh.state.epa.stars2.database.dbObjects.serviceCatalog.SCEmissionsReport scEmissionsReport)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsMaterialActionUnits> compareMaterials(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod period,
			java.lang.Integer percentDiff, java.lang.Integer origYear, java.lang.Integer compYear) throws java.rmi.RemoteException;

	public java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsMaterialActionUnits> processMaterialActions(
			int year,
			boolean submitted,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod period,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow[] rows)
			throws java.rmi.RemoteException;

	public boolean ntvDolaaApprove1(
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			int user)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvDolaaApprove2(
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			java.lang.String state, int user, boolean existingPurchaseOwner)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.lang.Integer conflictingReportForApproval(
			java.lang.String facilityId,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport approveReport(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.lang.String state,
			java.util.ArrayList<us.oh.state.epa.stars2.webcommon.reports.EmissionRow> emissions)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.invoice.Invoice buildInvoice(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			java.util.ArrayList<us.oh.state.epa.stars2.webcommon.reports.EmissionRow> emissions)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.invoice.Invoice buildInvoice(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
@Deprecated
	public us.oh.state.epa.stars2.webcommon.reports.ReportTemplates retrieveSCEmissionsReports(
			java.lang.Integer yr, java.lang.String contentType, boolean isTvA)
			throws java.rmi.RemoteException;

	public us.oh.state.epa.stars2.webcommon.reports.ReportTemplates retrieveSCEmissionsReports(
			java.lang.Integer yr, java.lang.String contentType, java.lang.String facilityId)
			throws java.rmi.RemoteException;

	public java.lang.Boolean missingReport(java.lang.String facilityId,
			int year, java.lang.Integer rptId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public boolean onlyOlderReports(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility fac,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public boolean noLaterTransferDates(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility fac,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvReport)
			throws java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport generateComparisonReport(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport compareReport)
			throws java.rmi.RemoteException;

	public void performTask(
			us.oh.state.epa.stars2.database.dbObjects.Task newTask,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws java.rmi.RemoteException;

	public void generateNewReport(
			us.oh.state.epa.stars2.database.dbObjects.Task newTask,
			us.oh.state.epa.stars2.database.dbObjects.Task facTask,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport oldRpt)
			throws java.rmi.RemoteException;

	public void generateNewNtvReport(
			us.oh.state.epa.stars2.database.dbObjects.Task newTask)
			throws java.rmi.RemoteException;

	public boolean retrieveCompliance(java.lang.Integer year,
			java.lang.String countyCd)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void setEsEis(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			java.lang.Integer year) throws java.rmi.RemoteException;

	public boolean reportable(
			us.oh.state.epa.stars2.database.dbObjects.facility.EmissionUnit e,
			int year,
			String contentTypeCd) throws java.rmi.RemoteException;

	public void locatePeriodNames(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report)
			throws java.rmi.RemoteException;

	public void explodeGroupsLocatePeriodNames(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report)
			throws java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport reportFacilityMatch(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.DefaultStackParms retrieveDefaultStackParms(
			java.lang.String sccId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow[] retrieveFireRows(
			java.lang.Integer year,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod p)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.PollutantPair[] retrievePollutantPartOf()
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public PollutantPair retrievePollutantParent(String pollutantCode) throws DAOException; 
	
	public void changeProfile(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.Task createRTask,
			us.oh.state.epa.stars2.database.dbObjects.Task oldFTask,
			us.oh.state.epa.stars2.database.dbObjects.Task replaceFTask,
			us.oh.state.epa.stars2.database.dbObjects.Task newFTask)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	/**
	 * Retrieve the emissions document identified by docId.
	 * 
	 * @param docId
	 * @return
	 * @throws DAOException
	 */
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef retrieveEmissionsDocument(
			java.lang.Integer docId, boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	/**
	 * Retrieve all emissions documents related to the report identified by
	 * rptId.
	 * 
	 * @param rptId
	 *            EmissionsReport identifier.
	 * @return
	 * @throws DAOException
	 */
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef[] retrieveEmissionsDocuments(
			java.lang.Integer rptId, boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	/**
	 * Create a zip file containing emissions inventory data and all its related
	 * attachments and download its contents.
	 * 
	 * @param emRptId
	 * @param attachmentList
	 * @param hideTradeSecret
	 * @param facilityId
	 * @param facilityDoc
	 * @param reportDoc
	 * @param reportSummaryDoc
	 * @param readOnly
	 * 
	 * @throws RemoteException
	 */
	public us.oh.state.epa.stars2.database.dbObjects.document.Document generateTempAttachmentZipFile(
			String emInventoryId, 
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef> attachmentList, 
			boolean hideTradeSecret,
			java.lang.String facilityId, 
			us.oh.state.epa.stars2.database.dbObjects.document.Document facilityDoc, 
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportDoc, 
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportSummaryDoc, 
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportSubmittedDoc, 
			boolean readOnly, java.sql.Timestamp submittedDate, boolean includeAllAttachments) 
			throws java.rmi.RemoteException;  	

	/**
	 * Load Document objects into all EmissionsDocumentRef objects associated
	 * with report.
	 * 
	 * @param report
	 * @param readOnly
	 * @throws DAOException
	 */
	public void loadAllDocuments(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	/**
	 * Load Document objects into docRef to avoid multiple queries for this
	 * information.
	 * 
	 * @param docRef
	 * @param readOnly
	 * @throws DAOException
	 */
	public void loadDocuments(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef docRef,
			boolean staging)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef uploadEmissionsDocument(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport rpt,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef doc,
			us.oh.state.epa.stars2.webcommon.UploadedFileInfo publicFile,
			us.oh.state.epa.stars2.webcommon.UploadedFileInfo tsFile,
			java.lang.Integer userId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef createEmissionsDocument(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef doc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.document.Document uploadDocument(
			us.oh.state.epa.stars2.database.dbObjects.document.Document doc,
			java.lang.String filename, java.io.InputStream is)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.MultiEstablishment[] facilitiesWithEisReports(
			int year)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.util.DbInteger[] locateUsingOldEuName(
			java.lang.String facilityId, int fpId, java.lang.String oldName)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.MultiEstablishment[] activeTvFacilities(
			int year)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public boolean modifyEmissionsDocument(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef doc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void removeEmissionsDocument(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef rptDoc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	/**
	 * Get list of documents associated with the TV/SMTV emission report.
	 * 
	 * @param
	 * @return
	 * @throws DAOException
	 */
	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.document.Document> getPrintableDocumentList(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.database.dbObjects.document.Document facilityDoc,
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportDoc, 
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportSummaryDoc,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.webcommon.reports.ReportTemplates scReports,
			java.lang.String user, boolean hideTradeSecret, boolean inStaging, boolean includeAllAttachments)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	/**
	 * Get list of documents associated with the TV/SMTV emission report.
	 * 
	 * @param
	 * @return
	 * @throws DAOException
	 */
	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.document.Document> getPrintableAttachmentList(
			us.oh.state.epa.stars2.database.dbObjects.document.Document facilityDoc, 
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportDoc, 
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportSummaryDoc, 
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocumentRef> atts,
			boolean hideTradeSecret, boolean inStaging, java.sql.Timestamp submittedDate, boolean includeAllAttachments)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	/**
	 * Get list of documents associated with the NTV emission report.
	 * 
	 * @param
	 * @return
	 * @throws DAOException
	 */
	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.document.Document> getPrintableDocumentList(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			us.oh.state.epa.stars2.webcommon.reports.NtvReport ntvRpt,
			us.oh.state.epa.stars2.database.dbObjects.document.TmpDocument reportDoc,
			java.lang.StringBuffer currentOwnersAddresses,
			java.lang.StringBuffer prevOwnerAddress,
			java.lang.StringBuffer newOwnerAddress,
			java.lang.StringBuffer currentBillingAddress,
			java.lang.StringBuffer newBillingAddress,
			java.lang.StringBuffer currentPrimaryAddress,
			java.lang.StringBuffer newPrimaryAddress,
			java.lang.Integer prevRptEvenYear,
			java.lang.Float prevRptEvenYearTons,
			java.lang.String prevRptEvenYearString,
			java.util.Collection<javax.faces.model.SelectItem> fee1PickList,
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionTotal> fer1,
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionTotal> es1,
			boolean nonAttain1,
			boolean incluldeES1,
			java.lang.Integer prevRptOddYear,
			java.lang.Float prevRptOddYearTons,
			java.lang.String prevRptOddYearString,
			java.util.Collection<javax.faces.model.SelectItem> fee2PickList,
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionTotal> fer2,
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionTotal> es2,
			boolean nonAttain2, boolean incluldeES2, java.lang.String user,
			boolean inStaging, boolean hideTradeSecret, boolean includeAllAttachments)
			throws java.rmi.RemoteException;
	
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow retrieveFireRow(
			java.lang.String fireId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow retrieveFireRow(
			java.lang.String sccId, java.lang.String materialCd, int year)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow[] retrieveFireRow(
			java.lang.String sccId, java.lang.String materialCd,
			java.lang.String pollutantCd, java.lang.String factor,
			java.lang.String formula, java.lang.String measure,
			java.lang.String action, int year)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow[] retrieveFireRow(
			java.lang.String sccId, java.lang.String materialCd,
			java.lang.String pollutantCd, java.lang.String factor,
			java.lang.String formula, java.lang.String measure,
			java.lang.String action, int year,
			boolean omitFactorAndFormula)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void removeInvalidFireRows(int year)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void deprecateFire(int date)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	public void deprecateFire(int date, String sccId, List<String> materialCds, List<String> pollutantCds)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.lang.Integer activeFireRows()
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FireRow[] deprecatedFireRows(
			int year)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.lang.String getDAPCAttestationMessage(
			java.lang.String permitClassCd,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report)
			throws java.rmi.RemoteException;

	/**
	 * Return pdf file RO can sign as attestation document.
	 * 
	 * @param repor
	 * @param facility
	 * @return
	 * @throws DAOException
	 */
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocument createEmissionsAttestationDocument(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	/**
	 * Add attestation document to application
	 * 
	 * @param app
	 * @param attestationDoc
	 * @param trans
	 * @throws DAOException
	 */
	public void addAttestationDocument(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsDocument attestationDoc,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void removeAttestationDocument(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void addSubmissionAttachments(
			us.oh.state.epa.stars2.database.dbObjects.Task task)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FacilityPermitInfo[] retrieveFacilityPermitInfo(
			java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.FacilityAppInfo[] retrieveFacilityAppInfo(
			java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public java.lang.String  generateTempDocument(us.oh.state.epa.stars2.webcommon.reports.ReportProfileBase rp, us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility, TemplateDocument templateDoc);
	
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportNote createNote(us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportNote note)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
		
	public boolean modifyNote(us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportNote note) 
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
				
	public us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReportPeriod[] retrieveEmissionPeriods(Integer reportId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
	
	public us.oh.state.epa.stars2.database.dbObjects.serviceCatalog.Fee[] getFeeinfo(Integer feeId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;		
	
	public String[] getSuperCd(String pollutantCd)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;	
	
		/**
	 * Set the "validated" flag for <code>report</code> to <code>validated</code>.
	 * This method exists to avoid a full update of all emissions report attributes
	 * when all that is needed is to set the validated flag.
	 * 
	 * @param report
	 *            the emissions report
	 * @param validated
	 *            <code>true</code> or <code>false</code> to indicate whether
	 *            the emissions report is validated.
	 * @return
	 * @throws DAOException
	 */
	public boolean setValidatedFlag(
			us.oh.state.epa.stars2.database.dbObjects.emissionReport.EmissionsReport report,
			boolean validated)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public List<EmissionCalcMethod> retrieveRecommendedMethods(EmissionRow line,
				EmissionsReport report, Facility facility, EmissionsReportPeriod period);

	public List<MissingFIREFactor> retrieveMissingFactors(int year, String facilityClass)
			throws DAOException;
	
	/**
     * @param year
     * @param report
     * @return
     * @throws DAOException
     */
	
	public boolean generateXML(UsEpaEisReport report) throws DAOException;
	
	/**
     * @param report
     * @param scReports
     * @param submitted
     * @return
     * @throws DAOException
     * @throws ApplicationException
     */
	public void updateTotalEmissions(EmissionsReport report, ReportTemplates scReports, boolean submitted)
			throws DAOException, ApplicationException;

	public List<ReportTemplates> retrieveAssociatedSCEmissionsReports(
			EmissionsReport report) throws DAOException;
	
	public List<ReportTemplates> retrieveAssociatedSCEmissionsReports(
			EmissionsReport report, boolean staging) throws DAOException;
	
	public void deleteEmissionsRptInfo(java.lang.String facilityId,
			java.lang.Integer id)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public Integer emissionsInventoriesForFacilityAndServiceCatalog(
			String facilityId, Integer serviceCatalogId);
	
	/**
	 * Returns all of the materials currently defined in the FIRE factor table for the
	 * SCC.
	 * 
	 * @return SimpleDef[] All reasons of this type.
	 * @throws DAOException
	 *             Database access error.
	 */
	public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleDef[] retrieveSccMaterials(
			java.lang.String sccId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	/**
	 * Returns all of the pollutants currently defined in the FIRE factor table for the
	 * SCC.
	 * 
	 * @return SimpleDef[] All reasons of this type.
	 * @throws DAOException
	 *             Database access error.
	 */
	public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleDef[] retrieveSccPollutants(
			java.lang.String sccId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	/**
	 * Returns all of the pollutants currently defined in the FIRE factor table for the
	 * SCC and material(s)
	 * 
	 * @return SimpleDef[] All reasons of this type.
	 * @throws DAOException
	 *             Database access error.
	 */
	public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleDef[] retrieveSccPollutants(
			java.lang.String sccId,
			java.util.List<java.lang.String> materialCds
			)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;
	
	/**
	 * @param tradeSecretDocId
	 * @return EmissionsDocumentRef
	 * @throws DAOException
	 */
	EmissionsDocumentRef retrieveReportDocumentByTradeSecrectDocId(Integer tradeSecretDocId) throws DAOException;
	
	/**
	 * 
	 * @param reportId
	 * @return EmissionsReport
	 * @throws DAOException
	 */
	EmissionsReport retrieveEmissionsReportById(Integer reportId) throws DAOException;

	List<EmissionsReport> createEmissionsReportFromCSV(final EiDataImport eiDataImport) 
			throws DAOException, ApplicationException;

	Attachment createEiDataImportAttachment(EiDataImportCriteria importCriteria, Attachment attachment,
			InputStream fileStream, Attachment tsAttachment, InputStream tsInputStream) throws DAOException;

	void removeEiDataImportAttachment(EiDataImportCriteria importCriteria, Attachment doc)
			throws DAOException, RemoteException;

	boolean isEmissionsReportBillable(List<ReportTemplates> scs) throws DAOException;


	EmissionsReport createEmissionsReportFromCSV(Facility facility, EmissionsReport newReport,
			List<ReportTemplates> scs) throws DAOException;

	Map<String, Integer> retrieveEnabledEmissionRptsForYearAndContentType(Integer year, String contentType)
			throws DAOException;

	public boolean deleteAssociatedInvoice(EmissionsReport emissionsReport) throws DAOException;

	public boolean deleteReferences(String facilityId) throws DAOException;

			
}
		

