/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

import us.oh.state.epa.stars2.database.dao.Transaction;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FacilityHistory;
import us.oh.state.epa.stars2.framework.exception.DAOException;

/**
 * Service interface for FacilityHistoryEJB.
 */
public interface FacilityHistoryService {

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FacilityHistory retrieveFacilityHistory(
			java.lang.Integer histId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FacilityHistory createFacilityHistory(
			java.lang.Integer fpId, us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyFacilityHistory(
			us.oh.state.epa.stars2.database.dbObjects.ceta.FacilityHistory fh)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void modifyCurrentFacilityHistory(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			int userId, boolean faciltySaveRequired)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void migrateFacilityHistory(
			us.oh.state.epa.stars2.database.dbObjects.facility.Facility facility,
			int userId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	public void deleteFacilityHistory(int facilityHistoryId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			java.rmi.RemoteException;

	FacilityHistory createFacilityHistory(FacilityHistory fh, Transaction trans)
			throws DAOException;


}
