/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

import java.sql.Timestamp;
import java.util.List;

import javax.faces.model.SelectItem;

import us.oh.state.epa.stars2.database.dbObjects.ceta.Evaluator;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FceAmbientMonitorLineItem;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FceApplicationSearchLineItem;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FceContinuousMonitorLineItem;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FceEmissionsInventoryLineItem;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FcePermitCondition;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FceStackTestSearchLineItem;
import us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval;
import us.oh.state.epa.stars2.database.dbObjects.ceta.SearchDateRange;
import us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit;
import us.oh.state.epa.stars2.database.dbObjects.complianceReport.ComplianceReportList;
import us.oh.state.epa.stars2.database.dbObjects.document.Correspondence;
import us.oh.state.epa.stars2.database.dbObjects.facility.Facility;
import us.oh.state.epa.stars2.database.dbObjects.infrastructure.Note;
import us.oh.state.epa.stars2.database.dbObjects.permit.Permit;
import us.oh.state.epa.stars2.database.dbObjects.permit.PermitConditionSearchLineItem;
import us.oh.state.epa.stars2.framework.exception.DAOException;
import us.wy.state.deq.impact.database.dbObjects.monitoring.Monitor;

/**
 * Service interface for FullComplianceEvalEJB.
 */
public interface FullComplianceEvalService {

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval retrieveFce(java.lang.String facilityId,
			java.lang.Integer fceId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval retrieveFceOnly(java.lang.Integer fceId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval retrieveFceOnly(java.lang.String inspId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.FceAttachment> retrieveFceAttachments(
			java.lang.Integer fceId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.SvAttachment> retrieveSvAttachments(
			java.lang.Integer visitId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public boolean isVisitDup(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit siteVisit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit retrieveSiteVisit(java.lang.Integer visitId)
			throws java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit[] retrieveSiteVisitsByFce(
			java.lang.String facilityId, java.lang.Integer fceId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void saveReassign(java.lang.Integer fceId, us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit[] visits)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval createFce(
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval newFce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval createFce(
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval newFCE,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval createMigratedFce(
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval newFce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval createMigratedFce(
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval newFce,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void createFceGetFpId(java.lang.String facilityId,
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval newFCE)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit createSiteVisit(
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit newVisit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit createSiteVisit(
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit newVisit,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit createMigratedSiteVisit(
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit newVisit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	/**
	 * FOR MIGRATION
	 * 
	 * @param newVisit
	 * @param trans
	 * @throws DAOException
	 * @return FullComplianceEval
	 */
	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit createMigratedSiteVisit(
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit newVisit,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifyFce(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifyFce(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifyFce(us.oh.state.epa.stars2.database.dbObjects.ceta.FceScheduleRow fceR)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifySiteVisit(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit visit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifySiteVisit(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit visit,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void removeFce(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void removeFce(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void removeSiteVisit(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit siteVisit)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void removeSiteVisit(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit siteVisit,
			us.oh.state.epa.stars2.database.dao.Transaction trans)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval[] retrieveFceBySearch(
			java.lang.String inspId, java.lang.String facilityId, java.lang.String facilityName,
			java.lang.String countyCd, java.lang.String doLaaCd, java.lang.String permitClassCd,
			java.lang.String facilityTypeCd, java.sql.Timestamp beginSched, java.sql.Timestamp endSched,
			java.sql.Timestamp beginDate, java.sql.Timestamp endDate, java.lang.Integer assignedStaff,
			java.lang.Integer evaluator, java.lang.String usEpaCommitted,
			java.util.List<java.lang.String> inspectionReportStateCds, String portable, java.lang.String cmpId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval[] retrieveFceBySearch(
			java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit[] retrieveVisitBySearch(java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit[] retrieveVisitBySearch(java.lang.String siteId,
			java.lang.String inspId, java.lang.String facilityId, java.sql.Timestamp beginDate,
			java.sql.Timestamp endDate, java.lang.String visitType, java.lang.String announced,
			java.lang.Integer evaluator, java.lang.String facilityName, java.lang.String doLaaCd,
			java.lang.String countyCd, java.lang.String permitClassCd, java.lang.String facilityTypeCd,
			java.lang.String cmpId, java.lang.String complianceIssued)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit[] searchSiteVisits(java.lang.String facilityId,
			java.sql.Timestamp beginDate, java.sql.Timestamp endDate)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.Evaluator> orderEvaluators(
			java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.Evaluator> eList)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.ArrayList<us.oh.state.epa.stars2.database.dbObjects.ceta.FceScheduleRow> needToSchedFce(
			java.lang.String facilityId, java.lang.String facilityNm, java.lang.String doLaaCd,
			java.lang.String countyCd, java.lang.String permitClassCd, java.lang.String facilityTypeCd,
			boolean schedOrNot, java.lang.Integer showThruFfy, boolean nonCommitted, java.lang.String cmpId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public int updateFceSched(java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.FceScheduleRow> fceSched)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.lang.Integer getUserId(java.lang.String name)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void removeFceAttachment(us.oh.state.epa.stars2.database.dbObjects.ceta.FceAttachment doc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void removeSvAttachment(us.oh.state.epa.stars2.database.dbObjects.ceta.SvAttachment doc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifyFceAttachment(us.oh.state.epa.stars2.database.dbObjects.ceta.FceAttachment doc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void modifySvAttachment(us.oh.state.epa.stars2.database.dbObjects.ceta.SvAttachment doc)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	/**
	 * Create a new row in the Attachment table.
	 * 
	 * @param fce
	 * @param attachment
	 * @param fileStream
	 * @return Attachment
	 */
	public us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment createFceAttachment(
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce,
			us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment attachment, java.io.InputStream fileStream)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * Create a new row in the Attachment table.
	 * 
	 * @param siteVisit
	 * @param attachment
	 * @param fileStream
	 * @return Attachment
	 */
	public us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment createSvAttachment(
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit siteVisit,
			us.oh.state.epa.stars2.database.dbObjects.attachments.Attachment attachment, java.io.InputStream fileStream)
			throws us.oh.state.epa.stars2.framework.exception.DAOException,
			us.oh.state.epa.stars2.framework.exception.ValidationException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit> newAfsSiteVisits()
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval> newAfsScheduledFCEs(
			java.sql.Timestamp beginSched, java.sql.Timestamp endSched)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval> newAfsFCEs()
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.lang.Integer afsLockFceComp(java.lang.String scscId,
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.lang.Integer afsLockFceSched(java.lang.String scscId,
			us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.lang.Integer afsLockSiteVisit(java.lang.String scscId,
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit sv)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public boolean afsSetDateSiteVisit(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit sv)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public boolean afsSetDateFceSched(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public boolean afsSetDateFceComp(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval> retrieveSchedFce(
			java.lang.String scscId, java.lang.String afsId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval> retrieveEvalFce(
			java.lang.String scscId, java.lang.String afsId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit> retrieveSiteVisitByAfsId(
			java.lang.String scscId, java.lang.String afsId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval retrieveLastCompletedFce(
			java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval retrieveLastScheduledFce(
			java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisit retrieveLastSiteVisit(java.lang.String facilityId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.AirProgramCompliance> complianceSearch(
			java.lang.String facilityId, java.lang.String facilityName, java.lang.String operatingStatusCd,
			java.lang.String doLaaCd, java.lang.String countyCd, java.util.List<java.lang.String> selectedC,
			java.util.List<java.lang.String> selectedSipList, java.util.List<java.lang.String> selectedMactList,
			java.util.List<java.lang.String> selectedTvList, java.util.List<java.lang.String> selectedSmList,
			java.util.List<java.lang.String> selectedNeshapsList, java.util.List<java.lang.String> selectedNspsList,
			java.util.List<java.lang.String> selectedPsdList, java.util.List<java.lang.String> selectedNsrList)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public void addMissingFceDir(us.oh.state.epa.stars2.database.dbObjects.ceta.FullComplianceEval fce)
			throws us.oh.state.epa.stars2.framework.exception.DAOException;

	public void fceNeedReminders()
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public Note[] retrieveInspectionNotes(int fceId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.InspectionNote createInspectionNote(
			us.oh.state.epa.stars2.database.dbObjects.ceta.InspectionNote inspectionNote)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	boolean modifyInspectionNote(us.oh.state.epa.stars2.database.dbObjects.ceta.InspectionNote inspectionNote)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public Note[] retrieveSiteVisitNotes(int visitId)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	public us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisitNote createSiteVisitNote(
			us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisitNote siteVisitNote)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	boolean modifySiteVisitNote(us.oh.state.epa.stars2.database.dbObjects.ceta.SiteVisitNote siteVisitNote)
			throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

	FullComplianceEval[] retrieveFceWithNoSiteVisitsOrStackTests(String facilityId) throws DAOException;

	void deleteAdditionalAQDStaffByFceId(Integer fceId) throws DAOException;

	void createAdditionalAQDStaff(Integer aqdStaffId, Integer fceId) throws DAOException;

	List<Evaluator> retrieveAdditionalAQDStaffByFceId(Integer fceId) throws DAOException;

	public FullComplianceEval retrieveLastPriorCompletedFce(String facilityId, Integer fceId) throws DAOException;

	public void prepareFce(FullComplianceEval fce) throws DAOException;

	public void completeFce(FullComplianceEval fce) throws DAOException, java.rmi.RemoteException;

	public void finalizeFce(FullComplianceEval fce) throws DAOException;

	public void modifyFceObservationsAndConcerns(FullComplianceEval fce) throws DAOException;

	List<SelectItem> getAllFinalPermits(FullComplianceEval fce) throws DAOException;

	public List<FceApplicationSearchLineItem> retrieveFceApplicationsBySearch(FullComplianceEval fce)
			throws DAOException;

	public List<FceApplicationSearchLineItem> retrieveFceApplicationsPreserved(FullComplianceEval fce)
			throws DAOException;

	public void updateFceApplicationsPreserved(FullComplianceEval fce) throws DAOException;

	public void clearFceApplicationsPreserved(FullComplianceEval fce) throws DAOException;

	public void addFceApplicationsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	public SearchDateRange retrieveFcePreservedSearchDateRange(Integer fceId, String snapshotTypeCd)
			throws DAOException;

	List<Integer> retrieveAssociatedPermitIdsByFceId(Integer fceId) throws DAOException;

	public void updateAssociatedPermits(FullComplianceEval fce, List<Integer> corrPermitIdsToAssociate,
			List<Integer> corrPermitIdsToDisassociate) throws DAOException;

	void deleteAssociatedPermitConditionIdRefByPermitIds(List<Integer> permitIds) throws DAOException;

	void associatePermitConditionsByPermitIds(List<Integer> permitIds, Integer fceId) throws DAOException;

	List<FcePermitCondition> retrieveAssociatedPermitConditionsByFceId(Integer fceId) throws DAOException;

	List<PermitConditionSearchLineItem> retrieveExcludedPermitConditionsByFceId(Integer fceId) throws DAOException;

	public List<Permit> retrieveFcePermitsBySearch(FullComplianceEval fce) throws DAOException;

	public void updateFcePermitsPreserved(FullComplianceEval fce) throws DAOException;

	public void clearFcePermitsPreserved(FullComplianceEval fce) throws DAOException;

	public void addFcePermitsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	public List<Permit> retrieveFcePermitsPreserved(FullComplianceEval fce) throws DAOException;

	void modifyAssociatedPermitConditionIdRef(List<FcePermitCondition> pcs) throws DAOException;

	void deleteAssociatedPermitConditionIdRefsByFceId(Integer fceId) throws DAOException;

	public void deleteAssociatedPermitConditionIds(Integer fceId, List<Integer> permitConditionsToExclude)
			throws DAOException;

	public void createAssociatedPermitConditionIds(Integer fceId, List<Integer> permitConditionsToExclude)
			throws DAOException;

	void updatePermitConditionSelections(FullComplianceEval fce, List<Integer> permitConditionsToInclude,
			List<Integer> permitConditionsToExclude) throws DAOException;

	//Stack test
	public List<FceStackTestSearchLineItem> retrieveFceStackTestsBySearch(FullComplianceEval fce) throws DAOException;

	public void updateFceStackTestsPreserved(FullComplianceEval fce) throws DAOException;

	public void clearFceStackTestsPreserved(FullComplianceEval fce) throws DAOException;

	public void addFceStackTestsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	public List<FceStackTestSearchLineItem> retrieveFceStackTestsPreserved(FullComplianceEval fce) throws DAOException;

	//Site Visits
	void addFceSiteVisitsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	void updateFceSiteVisitsPreserved(FullComplianceEval fce) throws DAOException;

	List<SiteVisit> retrieveFceSiteVisitsPreserved(FullComplianceEval fce) throws DAOException;

	void clearFceSiteVisitsPreserved(FullComplianceEval fce) throws DAOException;

	// Compliance
	public List<ComplianceReportList> retrieveFceComplianceReportBySearch(FullComplianceEval fce) throws DAOException;

	public void updateFceComplianceReportsPreserved(FullComplianceEval fce) throws DAOException;

	public void clearFceComplianceReportsPreserved(FullComplianceEval fce) throws DAOException;

	public void addFceComplianceReportsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	public List<ComplianceReportList> retrieveFceComplianceReportsPreserved(FullComplianceEval fce) throws DAOException;

	// Ambient Monitor
	List<FceAmbientMonitorLineItem> searchFacilityMonitorsByDate(FullComplianceEval fce) throws DAOException;

	void clearFceAmbientMonitorsPreserved(FullComplianceEval fce) throws DAOException;

	List<FceAmbientMonitorLineItem> retrieveFceAmbientMonitorsPreserved(FullComplianceEval fce) throws DAOException;

	void updateFceAmbientMonitorsPreserved(FullComplianceEval fce) throws DAOException;

	void addFceAmbientMonitorsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	// Correspondence
	public List<Correspondence> retrieveFceCorrespondenceBySearch(FullComplianceEval fce) throws DAOException;

	public void updateFceCorrespondencesPreserved(FullComplianceEval fce) throws DAOException;

	public void clearFceCorrespondencesPreserved(FullComplianceEval fce) throws DAOException;

	public void addFceCorrespondencesSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	public List<Correspondence> retrieveFceCorrespondencesPreserved(FullComplianceEval fce) throws DAOException;

	// Emissions Inventory
	public List<FceEmissionsInventoryLineItem> retrieveFceEmissionsInventoryBySearch(FullComplianceEval fce)
			throws DAOException;

	public void updateFceEmissionsInventoriesPreserved(FullComplianceEval fce) throws DAOException;

	public void clearFceEmissionsInventoriesPreserved(FullComplianceEval fce) throws DAOException;

	public void addFceEmissionsInventoriesSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	public List<FceEmissionsInventoryLineItem> retrieveFceEmissionsInventoriesPreserved(FullComplianceEval fce)
			throws DAOException;

	// CEM/COM/CMS snapshot
	List<FceContinuousMonitorLineItem> searchFacilityCemComLimitsByDate(FullComplianceEval fce) throws DAOException;

	void updateFceCemComLimitsPreserved(FullComplianceEval fce) throws DAOException;

	void clearFceCemComLimitsPreserved(FullComplianceEval fce) throws DAOException;

	void addFceCemComLimitsSnapshot(Integer fceId, Timestamp startDt, Timestamp endDt, List<Integer> ids)
			throws DAOException;

	List<FceContinuousMonitorLineItem> retrieveFceCemComLimitsPreserved(FullComplianceEval fce) throws DAOException;

	public void modifyFceReferenceReviewStartDate(FullComplianceEval fce) throws DAOException;
	
	public void associateRptWithCurrentFacility(FullComplianceEval fce, Facility currentfacility, Integer userId) throws DAOException;
	
	public void deletePreservedSnapshotRefs(Integer fceId) throws DAOException;
	
	public void deleteFcePermitRefs(Integer fceId) throws DAOException;
	
	public void clearLastInspIdByFacility(String facilityId) throws DAOException;
}
