/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

/**
 * Service interface for GDFEJB.
 */
public interface GDFService {

   public java.util.List<us.oh.state.epa.stars2.database.dbObjects.ceta.GDF> retrieveGDFs( java.lang.String doLaaCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ceta.GDF retrieveGDF( int gdfId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ceta.GDF retrieveGDF( java.lang.String doLaaCd,java.lang.String year,java.lang.String month )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ceta.GDF createGDF( us.oh.state.epa.stars2.database.dbObjects.ceta.GDF gdf )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void modifyGDF( us.oh.state.epa.stars2.database.dbObjects.ceta.GDF gdf )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void removeGDF( us.oh.state.epa.stars2.database.dbObjects.ceta.GDF gdf )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

}
