/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

/**
 * Service interface for GenericIssuanceEJB.
 */
public interface GenericIssuanceService {

   public us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance retrieveGenericIssuance( java.lang.Integer issuanceId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public java.util.List<us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance> searchGenericIssuances( java.lang.String facilityId,java.lang.Integer applicationId,java.lang.Integer permitId,java.lang.String typeCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance createGenericIssuance( us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance issuance )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void modifyGenericIssuance( us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance issuance )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.ValidationMessage[] issueGenericIssuance( us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance issuance,int userId,us.oh.state.epa.aport.admin.domain.User user )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void generateDocs( us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance issuance,java.lang.Integer userId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.document.CorrespondenceDocument uploadTempDocument( us.oh.state.epa.stars2.database.dbObjects.document.CorrespondenceDocument doc,java.io.InputStream is )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public void deleteGenericIssuance( us.oh.state.epa.stars2.database.dbObjects.genericIssuance.GenericIssuance issuance,java.lang.Integer userId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

}
