/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

/**
 * Service interface for PortalClientEJB.
 */
public interface PortalClientService
   
{

   public void processSubmittedTask( byte[] fromXmlTask )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public java.lang.String getFacilityId( us.oh.state.epa.stars2.util.FacilityIdReference facilityIdRef )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public java.lang.String getFacilityId( java.lang.String cityCd,java.lang.String cityName,java.lang.String countyCd,java.lang.String doLaaCd,java.lang.String doLaaId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public java.lang.Integer nextSequenceVal( java.lang.String sequenceId )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public java.lang.String processNewFacilityRequest( byte[] fromXmlTask )
		      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

}
