/*
 * Generated by XDoclet - Do not edit!
 */
package us.oh.state.epa.stars2.bo;

import us.oh.state.epa.stars2.framework.exception.DAOException;

/**
 * Service interface for ReportEJB.
 */
public interface ReportService {

	/**
    * Returns an array IssuanceDetails objects. IssuanceDetails are derrived data used to populate the Permit Issunace report.
    * @return issuanceDetail[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuanceDetails[] retrieveIssuanceDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array WorkflowDetails objects. IssuanceDetails are derrived data used to populate the Permit Issunace report.
    * @return issuanceDetail[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.WorkloadDetails[] retrieveWorkloadDetails( java.util.List<java.lang.String> doLaas,java.lang.String activityStatusCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveIssuedPermitsByDoLaaByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveExpiredPermitsByDoLaaByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveActivePermitsByDoLaaByType( java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaas,java.lang.Integer userId,java.lang.String activityName,java.lang.String activityStatusCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveIssuedPermitsByIssuanceType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveExpiredPermitsByIssuanceType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveActivePermitsByIssuanceType( java.lang.String permitType,java.lang.String doLaas,java.lang.Integer userId,java.lang.String activityName,java.lang.String activityStatusCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of ApplicationCount objects.
    * @return ApplicationCount[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.ApplicationCount[] retrieveApplicationCountByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of PermitCount objects.
    * @return PermitCount[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.PermitCount[] retrieveIssuedFinalPermitsCountByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of PBRCount objects.
    * @return PBRCount[]
    * @throws java.lang.Exception Database access error.
    */
   /*
   public us.oh.state.epa.stars2.database.dbObjects.report.PBRCount[] retrievePbrCountsByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
*/
   /**
    * Returns an array of FacilityPermitCount objects.
    * @return FacilityPermitCount[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.FacilityPermitCount[] retrieveFacilityCountsByPermitType( java.sql.Timestamp endDt )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of PermitTime objects.
    * @return FacilityPermitCount[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.PermitTime[] retrieveInProcessPermitTime(  )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of IssuancePtiDetails objects.
    * @return IssuancePtiDetails[]
    * @throws java.lang.Exception Database access error.
    */
   
   /*
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuancePtiDetails[] retrieveIssuancePtiDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
*/
   /**
    * Returns an array of IssuancePtiDetails objects.
    * @return IssuancePtiDetails[]
    * @throws java.lang.Exception Database access error.
    */
   /*
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuancePtiDetails[] retrieveExpiredPtiDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
*/
   /**
    * Returns an array of IssuancePtioDetails objects.
    * @return IssuancePtioDetails[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuancePtioDetails[] retrieveIssuancePtioDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of IssuancePtioDetails objects.
    * @return IssuancePtioDetails[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuancePtioDetails[] retrieveExpiredPtioDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,boolean hideShutdownFacility,boolean hideExemptPBR,boolean hideEUPermitStatusTRS,boolean hideEUExemptionDmPe,boolean hideEUShutdownInvalid,boolean hidePtoPtioEuActivePBR,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of IssuanceSptoDetails objects.
    * @return IssuanceSptoDetails[]
    * @throws java.lang.Exception Database access error.
    */
   /*
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuanceSptoDetails[] retrieveExpiredSptoDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,boolean hideShutdownFacility,boolean hideExemptPBR,boolean hideEUPermitStatusTRS,boolean hideEUExemptionDmPe,boolean hideEUShutdownInvalid,boolean hidePtoPtioEuActivePBR,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
*/
   /**
    * Returns an array of IssuanceTvDetails objects.
    * @return IssuanceTvDetails[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuanceTvDetails[] retrieveIssuanceTvDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of IssuanceTvDetails objects.
    * @return IssuanceTvDetails[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuanceTvDetails[] retrieveExpiredTvDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName,boolean hideShutdownFacility,boolean hideExemptPBR,boolean hideEUPermitStatusTRS,boolean hideEUExemptionDmPe,boolean hideEUShutdownInvalid,boolean hidePtoPtioEuActivePBR,java.lang.String issuanceType )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of IssuancePbrDetails objects.
    * @return IssuancePbrDetails[]
    * @throws java.lang.Exception Database access error.
    */
   /*
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuancePbrDetails[] retrieveIssuancePbrDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
*/
   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveIssuedPermitsByGeneralByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveExpiredPermitsByGeneralByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveActivePermitsByGeneralByType( java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaas,java.lang.Integer userId,java.lang.String activityName,java.lang.String activityStatusCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveIssuedPermitsByReasonByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveExpiredPermitsByReasonByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveActivePermitsByReasonByType( java.lang.String permitType,java.lang.String issuanceState,java.lang.String doLaas,java.lang.Integer userId,java.lang.String activityName,java.lang.String activityStatusCd )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveIssuedPermitsByDirectFinalByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array of SimepleIdDef objects.
    * @return SimpleIdDef[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.infrastructure.SimpleIdDef[] retrieveExpiredPermitsByDirectFinalByType( java.sql.Timestamp startDt,java.sql.Timestamp endDt,java.lang.String permitType,java.lang.String issuanceType,java.lang.String doLaaName )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.workflow.ProcessActivity[] retrieveActivityList( us.oh.state.epa.stars2.database.dbObjects.workflow.ProcessActivity pa,java.lang.String doLaas )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array PermitSOPData objects. PermitSOPData are derrived data used to populate the Permit SOP report.
    * @param showNotes
    * @return PermitSOPData[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.PermitSOPData[] retrievePermitSOPData( java.util.List<java.lang.String> doLaas,java.util.List<java.lang.String> permitTypes,java.util.List<java.lang.String> reasonCds,boolean general,boolean express,boolean hideShutdownFacility,boolean hideDeadEndedPermit,boolean hideShutDownInvalidEU,boolean backlogged,boolean showAll,java.lang.String type,boolean showNotes )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns an array PermitSOPData objects. PermitSOPData are derived data used to populate the LAte Permits report.
    * @return PermitSOPData[]
    * @throws java.lang.Exception Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.PermitSOPData[] retrieveLatePermitsData( java.util.List<java.lang.String> doLaas,java.util.List<java.lang.String> permitTypes,java.util.List<java.lang.String> reasonCds,boolean general,boolean express,boolean showAll,java.lang.String type )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.report.PermitSOPData[] retrievePreliminaryReviewCompletedData( java.util.List<java.lang.String> doLaas,java.util.List<java.lang.String> permitTypes,java.util.List<java.lang.String> reasonCds,java.sql.Timestamp fromDate,java.sql.Timestamp toDate )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.report.IssuedMetricsData[] retrieveIssuedMetricsData( java.util.List<java.lang.String> doLaas,java.lang.String permitType,java.util.List<java.lang.String> reasonCds,java.util.List<java.lang.String> countyCds,java.util.List<java.lang.String> selectedPermitActionTypes, java.lang.String dateBy, java.sql.Timestamp fromDate,java.sql.Timestamp toDate,boolean showNotes )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;
   
   public us.oh.state.epa.stars2.database.dbObjects.report.IssuedMetricsData[] retrieveNotIssuedMetricsData( java.util.List<java.lang.String> doLaas,java.lang.String permitType,java.util.List<java.lang.String> reasonCds,java.util.List<java.lang.String> countyCds,java.util.List<java.lang.String> selectedPermitActionTypes,java.lang.String dateBy, java.sql.Timestamp fromDate,java.sql.Timestamp toDate,boolean showNotes, boolean excludeDeadEnded, boolean excludeIssuedWithdrawal )
		      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   /**
    * Returns a TopsData object used to populate the U.S EPA TOPS report.
    * @return TOPSData
    * @throws DAOException Database access error.
    */
   public us.oh.state.epa.stars2.database.dbObjects.report.TOPSData retrieveTOPSData( java.sql.Timestamp reportDate )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.report.PermitExpirationDetails[] retrievePermitExpirationDetails( java.sql.Timestamp startDt,java.sql.Timestamp endDt,boolean hideShutdownFacility,boolean hideExemptPBR,boolean hideEUPermitStatusTRS,boolean hideEUExemptionDmPe,boolean hideEUShutdownInvalid,boolean hidePtoPtioEuActivePBR )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.report.WorkloadTrend[] retrieveWorkloadTrendReport( java.lang.String[] permitTypes,java.lang.String[] permitReasons )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

   public us.oh.state.epa.stars2.database.dbObjects.report.GenericIssuanceCount[] retrieveGenericIssuanceCount( java.lang.String[] doLaaCds,java.lang.String[] issuanceTypeCds,java.sql.Timestamp startDt,java.sql.Timestamp endDt )
      throws us.oh.state.epa.stars2.framework.exception.DAOException, java.rmi.RemoteException;

}
