/*
This script should be run against the IMPACT_SHARE database on the
SQL Server that will host the sharing tables for IMPACT. 

The script should be run after the transactional replication of the
sharing tables between each partner and sharing tables database has
been setup, and after the first successful synchonization.

Prior to running this script, the following databases should have
been created on the server, otherwise the script will fail:
	- GRIC_IMPACT_SHARE
	- MARICOPA_IMPACT_SHARE
	- PIMA_IMPACT_SHARE
	- PINAL_IMPACT_SHARE
	- FMYN_IMPACT_SHARE
	- IMPACT_SHARE

The script will create following objects in the IMPACT_SHARE
database:
	- Views
		- dbo.COMPANY
		- dbo.EMISSION_PERIOD
		- dbo.EMISSION_UNIT
		- dbo.EMISSION_UNIT_DETAIL
		- dbo.EMISSIONS
		- dbo.EU_PROCESS
		- dbo.FACILITY
		- dbo.FACILITY_X_NAICS
		- dbo.FP_EGRESS_POINT
		- dbo.FP_FACILITY
		- dbo.RELEASE_POINT
		- dbo.RELEASE_POINT_APPORTIONMENT

	- Stored Procedures
		- dbo.ExtractDispersionModelingData
		- dbo.SearchFacilitiesByAreaAndPollutant

	The views and stored proceddures together implement the requirements
	for the sharing table feature
*/

USE [IMPACT_SHARE]
GO

-- view dbo.COMPANY start
DROP VIEW IF EXISTS [dbo].[COMPANY]
GO

CREATE VIEW [dbo].[COMPANY] AS
	SELECT 
		N'GRIC' AS PARTNER_ID
		, cmp.COMPANY_ID
		, cmp.CMP_ID
		, cmp.NAME
		, cmp.ALIAS
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ZIP5
		, addr.COUNTRY_CD
		, ccd.COUNTRY_DSC 
	FROM GRIC_IMPACT_SHARE.dbo.CM_COMPANY cmp
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = cmp.ADDRESS_ID
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_COUNTRY_DEF ccd ON ccd.COUNTRY_CD = addr.COUNTRY_CD

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, cmp.COMPANY_ID
		, cmp.CMP_ID
		, cmp.NAME
		, cmp.ALIAS
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ZIP5
		, addr.COUNTRY_CD
		, ccd.COUNTRY_DSC 
	FROM MARICOPA_IMPACT_SHARE.dbo.CM_COMPANY cmp
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = cmp.ADDRESS_ID
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_COUNTRY_DEF ccd ON ccd.COUNTRY_CD = addr.COUNTRY_CD

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, cmp.COMPANY_ID
		, cmp.CMP_ID
		, cmp.NAME
		, cmp.ALIAS
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ZIP5
		, addr.COUNTRY_CD
		, ccd.COUNTRY_DSC 
	FROM PIMA_IMPACT_SHARE.dbo.CM_COMPANY cmp
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = cmp.ADDRESS_ID
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_COUNTRY_DEF ccd ON ccd.COUNTRY_CD = addr.COUNTRY_CD

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, cmp.COMPANY_ID
		, cmp.CMP_ID
		, cmp.NAME
		, cmp.ALIAS
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ZIP5
		, addr.COUNTRY_CD
		, ccd.COUNTRY_DSC 
	FROM PINAL_IMPACT_SHARE.dbo.CM_COMPANY cmp
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = cmp.ADDRESS_ID
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_COUNTRY_DEF ccd ON ccd.COUNTRY_CD = addr.COUNTRY_CD

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, cmp.COMPANY_ID
		, cmp.CMP_ID
		, cmp.NAME
		, cmp.ALIAS
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ZIP5
		, addr.COUNTRY_CD
		, ccd.COUNTRY_DSC 
	FROM FMYN_IMPACT_SHARE.dbo.CM_COMPANY cmp
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = cmp.ADDRESS_ID
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_COUNTRY_DEF ccd ON ccd.COUNTRY_CD = addr.COUNTRY_CD
GO
-- view dbo.COMPANY end

-- view dbo.FACILITY start
DROP VIEW IF EXISTS [dbo].[FACILITY]
GO

CREATE VIEW [dbo].[FACILITY] AS
	SELECT 
		N'GRIC' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fp.FACILITY_DESC
		, '' AS PERMIT_NMBR
		, '' AS EPA_REGISTRY_ID
		, fcx.COMPANY_ID
		, fp.PERMIT_CLASSIFICATION_CD
		, pcd.PERMIT_CLASSIFICATION_DSC
		, fp.CERR_CLASS_CD
		, fcd.CERR_CLASS_DESC
		, fp.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, addr.LATITUDE 
		, addr.LONGITUDE
		, addr.QUARTER
		, addr.QUARTER_QUARTER
		, addr.SECTION
		, addr.TOWNSHIP
		, addr.RANGE
		, addr.COUNTY_CD
		, ccd.COUNTY_NM
		, '' AS PARCEL
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.ZIP5
		, fp.START_DT
		, '' AS TRIBE 
	FROM GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY_COMPANY_XREF fcx ON fcx.FACILITY_ID = fp.FACILITY_ID 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_PERMIT_CLASSIFICATION_DEF pcd ON pcd.PERMIT_CLASSIFICATION_CD = fp.PERMIT_CLASSIFICATION_CD 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_CERR_CLASS_DEF fcd ON fcd.CERR_CLASS_CD = fp.CERR_CLASS_CD 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = fp.OPERATING_STATUS_CD 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_COUNTY_DEF ccd ON ccd.COUNTY_CD = addr.COUNTY_CD 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD 
	WHERE 
		fp.VERSION_ID = -1 
		AND fcx.END_DATE IS NULL
		AND addr.END_DT IS NULL 

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fp.FACILITY_DESC
		, '' AS PERMIT_NMBR
		, '' AS EPA_REGISTRY_ID
		, fcx.COMPANY_ID
		, fp.PERMIT_CLASSIFICATION_CD
		, pcd.PERMIT_CLASSIFICATION_DSC
		, fp.CERR_CLASS_CD
		, fcd.CERR_CLASS_DESC
		, fp.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, addr.LATITUDE 
		, addr.LONGITUDE
		, addr.QUARTER
		, addr.QUARTER_QUARTER
		, addr.SECTION
		, addr.TOWNSHIP
		, addr.RANGE
		, addr.COUNTY_CD
		, ccd.COUNTY_NM
		, '' AS PARCEL
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.ZIP5
		, fp.START_DT
		, '' AS TRIBE 
	FROM MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY_COMPANY_XREF fcx ON fcx.FACILITY_ID = fp.FACILITY_ID 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_PERMIT_CLASSIFICATION_DEF pcd ON pcd.PERMIT_CLASSIFICATION_CD = fp.PERMIT_CLASSIFICATION_CD 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_CERR_CLASS_DEF fcd ON fcd.CERR_CLASS_CD = fp.CERR_CLASS_CD 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = fp.OPERATING_STATUS_CD 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_COUNTY_DEF ccd ON ccd.COUNTY_CD = addr.COUNTY_CD 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD 
	WHERE 
		fp.VERSION_ID = -1 
		AND fcx.END_DATE IS NULL
		AND addr.END_DT IS NULL 

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fp.FACILITY_DESC
		, '' AS PERMIT_NMBR
		, '' AS EPA_REGISTRY_ID
		, fcx.COMPANY_ID
		, fp.PERMIT_CLASSIFICATION_CD
		, pcd.PERMIT_CLASSIFICATION_DSC
		, fp.CERR_CLASS_CD
		, fcd.CERR_CLASS_DESC
		, fp.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, addr.LATITUDE 
		, addr.LONGITUDE
		, addr.QUARTER
		, addr.QUARTER_QUARTER
		, addr.SECTION
		, addr.TOWNSHIP
		, addr.RANGE
		, addr.COUNTY_CD
		, ccd.COUNTY_NM
		, '' AS PARCEL
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.ZIP5
		, fp.START_DT
		, '' AS TRIBE 
	FROM PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY_COMPANY_XREF fcx ON fcx.FACILITY_ID = fp.FACILITY_ID 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_PERMIT_CLASSIFICATION_DEF pcd ON pcd.PERMIT_CLASSIFICATION_CD = fp.PERMIT_CLASSIFICATION_CD 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_CERR_CLASS_DEF fcd ON fcd.CERR_CLASS_CD = fp.CERR_CLASS_CD 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = fp.OPERATING_STATUS_CD 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_COUNTY_DEF ccd ON ccd.COUNTY_CD = addr.COUNTY_CD 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD 
	WHERE 
		fp.VERSION_ID = -1 
		AND fcx.END_DATE IS NULL
		AND addr.END_DT IS NULL 

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fp.FACILITY_DESC
		, '' AS PERMIT_NMBR
		, '' AS EPA_REGISTRY_ID
		, fcx.COMPANY_ID
		, fp.PERMIT_CLASSIFICATION_CD
		, pcd.PERMIT_CLASSIFICATION_DSC
		, fp.CERR_CLASS_CD
		, fcd.CERR_CLASS_DESC
		, fp.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, addr.LATITUDE 
		, addr.LONGITUDE
		, addr.QUARTER
		, addr.QUARTER_QUARTER
		, addr.SECTION
		, addr.TOWNSHIP
		, addr.RANGE
		, addr.COUNTY_CD
		, ccd.COUNTY_NM
		, '' AS PARCEL
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.ZIP5
		, fp.START_DT
		, '' AS TRIBE 
	FROM PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY_COMPANY_XREF fcx ON fcx.FACILITY_ID = fp.FACILITY_ID 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_PERMIT_CLASSIFICATION_DEF pcd ON pcd.PERMIT_CLASSIFICATION_CD = fp.PERMIT_CLASSIFICATION_CD 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_CERR_CLASS_DEF fcd ON fcd.CERR_CLASS_CD = fp.CERR_CLASS_CD 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = fp.OPERATING_STATUS_CD 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_COUNTY_DEF ccd ON ccd.COUNTY_CD = addr.COUNTY_CD 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD 
	WHERE 
		fp.VERSION_ID = -1 
		AND fcx.END_DATE IS NULL
		AND addr.END_DT IS NULL 

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fp.FACILITY_DESC
		, '' AS PERMIT_NMBR
		, '' AS EPA_REGISTRY_ID
		, fcx.COMPANY_ID
		, fp.PERMIT_CLASSIFICATION_CD
		, pcd.PERMIT_CLASSIFICATION_DSC
		, fp.CERR_CLASS_CD
		, fcd.CERR_CLASS_DESC
		, fp.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, addr.LATITUDE 
		, addr.LONGITUDE
		, addr.QUARTER
		, addr.QUARTER_QUARTER
		, addr.SECTION
		, addr.TOWNSHIP
		, addr.RANGE
		, addr.COUNTY_CD
		, ccd.COUNTY_NM
		, '' AS PARCEL
		, addr.STATE_CD
		, csd.STATE_NM
		, addr.ADDRESS1
		, addr.ADDRESS2
		, addr.CITY
		, addr.ZIP5
		, fp.START_DT
		, '' AS TRIBE 
	FROM FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY_COMPANY_XREF fcx ON fcx.FACILITY_ID = fp.FACILITY_ID 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_PERMIT_CLASSIFICATION_DEF pcd ON pcd.PERMIT_CLASSIFICATION_CD = fp.PERMIT_CLASSIFICATION_CD 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_CERR_CLASS_DEF fcd ON fcd.CERR_CLASS_CD = fp.CERR_CLASS_CD 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = fp.OPERATING_STATUS_CD 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_COUNTY_DEF ccd ON ccd.COUNTY_CD = addr.COUNTY_CD 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_STATE_DEF csd ON csd.STATE_CD = addr.STATE_CD 
	WHERE 
		fp.VERSION_ID = -1 
		AND fcx.END_DATE IS NULL
		AND addr.END_DT IS NULL 
GO
-- view dbo.FACILITY end

-- view dbo.FP_FACILITY start
DROP VIEW IF EXISTS [dbo].[FP_FACILITY]
GO

CREATE VIEW [dbo].[FP_FACILITY] AS
	SELECT 
		N'GRIC' AS PARTNER_ID
		, fp.* 
		, addr.LATITUDE
		, addr.LONGITUDE
		FROM GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp
		LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
		LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, fp.* 
		, addr.LATITUDE
		, addr.LONGITUDE
		FROM MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp
		LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
		LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	
	UNION ALL
	
	SELECT 
		N'PIMA' AS PARTNER_ID
		, fp.* 
		, addr.LATITUDE
		, addr.LONGITUDE
		FROM PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp
		LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
		LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	
	UNION ALL
	
	SELECT
		N'PINAL' AS PARTNER_ID
		, fp.* 
		, addr.LATITUDE
		, addr.LONGITUDE
		FROM PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp
		LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
		LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
	
	UNION ALL
	
	SELECT 
		N'FMYN' AS PARTNER_ID
		, fp.* 
		, addr.LATITUDE
		, addr.LONGITUDE
		FROM FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp
		LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY_ADDRESS_XREF fax ON fax.FP_ID = fp.FP_ID 
		LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.CM_ADDRESS addr ON addr.ADDRESS_ID = fax.ADDRESS_ID 
GO
-- view dbo.FP_FACILITY end

-- view dbo.FACILITY_X_NAICS start
DROP VIEW IF EXISTS [dbo].[FACILITY_X_NAICS]
GO

CREATE VIEW dbo.FACILITY_X_NAICS AS 
	SELECT 
		N'GRIC' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fnx.NAICS_CD
		, fnd.NAICS_DSC 
	FROM GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY_NAICS_XREF fnx ON fnx.FP_ID = fp.FP_ID 
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_NAICS_DEF fnd ON fnd.NAICS_CD = fnx.NAICS_CD 
	WHERE fp.VERSION_ID = -1 

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fnx.NAICS_CD
		, fnd.NAICS_DSC 
	FROM MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY_NAICS_XREF fnx ON fnx.FP_ID = fp.FP_ID 
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_NAICS_DEF fnd ON fnd.NAICS_CD = fnx.NAICS_CD 
	WHERE fp.VERSION_ID = -1 

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fnx.NAICS_CD
		, fnd.NAICS_DSC 
	FROM PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY_NAICS_XREF fnx ON fnx.FP_ID = fp.FP_ID 
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_NAICS_DEF fnd ON fnd.NAICS_CD = fnx.NAICS_CD 
	WHERE fp.VERSION_ID = -1 

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fnx.NAICS_CD
		, fnd.NAICS_DSC 
	FROM PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY_NAICS_XREF fnx ON fnx.FP_ID = fp.FP_ID 
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_NAICS_DEF fnd ON fnd.NAICS_CD = fnx.NAICS_CD 
	WHERE fp.VERSION_ID = -1 

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, fnx.NAICS_CD
		, fnd.NAICS_DSC 
	FROM FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY_NAICS_XREF fnx ON fnx.FP_ID = fp.FP_ID 
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_NAICS_DEF fnd ON fnd.NAICS_CD = fnx.NAICS_CD 
	WHERE fp.VERSION_ID = -1 
GO
-- view dbo.FACILITY_X_NAICS end

-- view dbo.EMISSION_UNIT start
DROP VIEW IF EXISTS [dbo].[EMISSION_UNIT]
GO

CREATE VIEW dbo.EMISSION_UNIT AS 
	SELECT 
		N'GRIC' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_TYPE_CD
		, eutd.EU_TYPE_NAME
		, eutd.EU_TYPE_DESC
		, feu.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, feu.INITIAL_INSTALLATION_DT
		, feu.INITIAL_STARTUP_DT
		, feu.INSTALL_DT
		, feu.STARTUP_DT 
	FROM GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSION_TYPE_DEF eutd ON eutd.EU_TYPE_CD = feu.EU_TYPE_CD 
	LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = feu.OPERATING_STATUS_CD 
	WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_TYPE_CD
		, eutd.EU_TYPE_NAME
		, eutd.EU_TYPE_DESC
		, feu.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, feu.INITIAL_INSTALLATION_DT
		, feu.INITIAL_STARTUP_DT
		, feu.INSTALL_DT
		, feu.STARTUP_DT 
	FROM MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSION_TYPE_DEF eutd ON eutd.EU_TYPE_CD = feu.EU_TYPE_CD 
	LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = feu.OPERATING_STATUS_CD 
	WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_TYPE_CD
		, eutd.EU_TYPE_NAME
		, eutd.EU_TYPE_DESC
		, feu.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, feu.INITIAL_INSTALLATION_DT
		, feu.INITIAL_STARTUP_DT
		, feu.INSTALL_DT
		, feu.STARTUP_DT 
	FROM PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSION_TYPE_DEF eutd ON eutd.EU_TYPE_CD = feu.EU_TYPE_CD 
	LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = feu.OPERATING_STATUS_CD 
	WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_TYPE_CD
		, eutd.EU_TYPE_NAME
		, eutd.EU_TYPE_DESC
		, feu.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, feu.INITIAL_INSTALLATION_DT
		, feu.INITIAL_STARTUP_DT
		, feu.INSTALL_DT
		, feu.STARTUP_DT 
	FROM PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSION_TYPE_DEF eutd ON eutd.EU_TYPE_CD = feu.EU_TYPE_CD 
	LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = feu.OPERATING_STATUS_CD 
	WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, fp.FP_ID
		, fp.FACILITY_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_TYPE_CD
		, eutd.EU_TYPE_NAME
		, eutd.EU_TYPE_DESC
		, feu.OPERATING_STATUS_CD
		, osd.OPERATING_STATUS_DSC
		, feu.INITIAL_INSTALLATION_DT
		, feu.INITIAL_STARTUP_DT
		, feu.INSTALL_DT
		, feu.STARTUP_DT 
	FROM FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSION_TYPE_DEF eutd ON eutd.EU_TYPE_CD = feu.EU_TYPE_CD 
	LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_OPERATING_STATUS_DEF osd ON osd.OPERATING_STATUS_CD = feu.OPERATING_STATUS_CD 
	WHERE fp.VERSION_ID = -1
GO
-- view dbo.EMISSION_UNIT end

-- view dbo.EMISSION_UNIT_DETAIL start
DROP VIEW IF EXISTS [dbo].[EMISSION_UNIT_DETAIL]
GO

CREATE VIEW dbo.EMISSION_UNIT_DETAIL AS 
	SELECT 
		N'GRIC' AS PARTNER_ID
		, feut.*
		FROM GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT_TYPE feut
		INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = feut.EMU_ID 
		INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
		WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, feut.*
		FROM MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT_TYPE feut
		INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = feut.EMU_ID 
		INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
		WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, feut.*
		FROM PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT_TYPE feut
		INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = feut.EMU_ID 
		INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
		WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, feut.*
		FROM PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT_TYPE feut
		INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = feut.EMU_ID 
		INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
		WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, feut.*
		FROM FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT_TYPE feut
		INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = feut.EMU_ID 
		INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
		WHERE fp.VERSION_ID = -1
GO
-- view dbo.EMISSION_UNIT_DETAIL end

-- view dbo.EU_PROCESS start
DROP VIEW IF EXISTS [dbo].[EU_PROCESS]
GO

CREATE VIEW dbo.EU_PROCESS AS 
	SELECT 
		N'GRIC' AS PARTNER_ID
		, fp.FACILITY_ID
		, fp.FP_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_DESC
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, fep.PROCESS_ID
		, fep.PROCESS_NAME
		, fep.EMISSION_PROCESS_DSC
		, fep.SCC_ID
		, scc.LEVEL1_DSC
		, scc.LEVEL2_DSC
		, scc.LEVEL3_DSC
		, scc.LEVEL4_DSC 
	FROM GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID 
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN GRIC_IMPACT_SHARE.dbo.CM_SCC scc ON scc.SCC_ID = fep.SCC_ID 
	WHERE fp.VERSION_ID = -1 

	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, fp.FACILITY_ID
		, fp.FP_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_DESC
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, fep.PROCESS_ID
		, fep.PROCESS_NAME
		, fep.EMISSION_PROCESS_DSC
		, fep.SCC_ID
		, scc.LEVEL1_DSC
		, scc.LEVEL2_DSC
		, scc.LEVEL3_DSC
		, scc.LEVEL4_DSC 
	FROM MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID 
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_SCC scc ON scc.SCC_ID = fep.SCC_ID 
	WHERE fp.VERSION_ID = -1 

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, fp.FACILITY_ID
		, fp.FP_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_DESC
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, fep.PROCESS_ID
		, fep.PROCESS_NAME
		, fep.EMISSION_PROCESS_DSC
		, fep.SCC_ID
		, scc.LEVEL1_DSC
		, scc.LEVEL2_DSC
		, scc.LEVEL3_DSC
		, scc.LEVEL4_DSC 
	FROM PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID 
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN PIMA_IMPACT_SHARE.dbo.CM_SCC scc ON scc.SCC_ID = fep.SCC_ID 
	WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, fp.FACILITY_ID
		, fp.FP_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_DESC
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, fep.PROCESS_ID
		, fep.PROCESS_NAME
		, fep.EMISSION_PROCESS_DSC
		, fep.SCC_ID
		, scc.LEVEL1_DSC
		, scc.LEVEL2_DSC
		, scc.LEVEL3_DSC
		, scc.LEVEL4_DSC 
	FROM PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID 
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN PINAL_IMPACT_SHARE.dbo.CM_SCC scc ON scc.SCC_ID = fep.SCC_ID 
	WHERE fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, fp.FACILITY_ID
		, fp.FP_ID
		, fp.FACILITY_NM
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_DESC
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, fep.PROCESS_ID
		, fep.PROCESS_NAME
		, fep.EMISSION_PROCESS_DSC
		, fep.SCC_ID
		, scc.LEVEL1_DSC
		, scc.LEVEL2_DSC
		, scc.LEVEL3_DSC
		, scc.LEVEL4_DSC 
	FROM FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID 
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID 
	INNER JOIN FMYN_IMPACT_SHARE.dbo.CM_SCC scc ON scc.SCC_ID = fep.SCC_ID 
	WHERE fp.VERSION_ID = -1
GO
-- view dbo.EU_PROCESS end

-- view dbo.RELEASE_POINT start
DROP VIEW IF EXISTS [dbo].[RELEASE_POINT]
GO

CREATE VIEW dbo.RELEASE_POINT AS 
	SELECT 
		N'GRIC' AS PARTNER_ID
		, fep.EMU_ID
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, egp.FPNODE_ID AS RELEASEPOINT_FPNODE_ID
		, egp.EGRESS_POINT_TYPE_CD
		, egp.DAPC_DSC
		, egp.REGULATED_USER_DSC
		, egp.OPERATING_STATUS_CD
		, egp.LAT_DEG
		, egp.LONG_DEG
		, egp.RELEASE_HEIGHT
		, egp.BASE_ELEVATION
		, egp.HEIGHT
		, egp.DIAMETER
		, egp.EXIT_GAS_VELOCITY
		, egp.EXIT_GAS_TEMP_MAX
		, egp.EXIT_GAS_TEMP_AVG
		, egp.EXIT_GAS_FLOW_MAX
		, egp.EXIT_GAS_FLOW_AVG
		, rpa.RELEASE_POINT_APPORTIONMENT 
	FROM GRIC_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep
	CROSS APPLY GRIC_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa 
	CROSS APPLY GRIC_IMPACT_SHARE.dbo.FP_EGRESS_POINT egp 
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = fep.EMU_ID
	INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
	WHERE 
		egp.FPNODE_ID = rpa.TO_FPNODE_ID 
		AND fp.VERSION_ID = -1
	
	UNION ALL

	SELECT 
		N'MARICOPA' AS PARTNER_ID
		, fep.EMU_ID
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, egp.FPNODE_ID AS RELEASEPOINT_FPNODE_ID
		, egp.EGRESS_POINT_TYPE_CD
		, egp.DAPC_DSC
		, egp.REGULATED_USER_DSC
		, egp.OPERATING_STATUS_CD
		, egp.LAT_DEG
		, egp.LONG_DEG
		, egp.RELEASE_HEIGHT
		, egp.BASE_ELEVATION
		, egp.HEIGHT
		, egp.DIAMETER
		, egp.EXIT_GAS_VELOCITY
		, egp.EXIT_GAS_TEMP_MAX
		, egp.EXIT_GAS_TEMP_AVG
		, egp.EXIT_GAS_FLOW_MAX
		, egp.EXIT_GAS_FLOW_AVG
		, rpa.RELEASE_POINT_APPORTIONMENT 
	FROM MARICOPA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep
	CROSS APPLY MARICOPA_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa 
	CROSS APPLY MARICOPA_IMPACT_SHARE.dbo.FP_EGRESS_POINT egp 
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = fep.EMU_ID
	INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
	WHERE 
		egp.FPNODE_ID = rpa.TO_FPNODE_ID 
		AND fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PIMA' AS PARTNER_ID
		, fep.EMU_ID
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, egp.FPNODE_ID AS RELEASEPOINT_FPNODE_ID
		, egp.EGRESS_POINT_TYPE_CD
		, egp.DAPC_DSC
		, egp.REGULATED_USER_DSC
		, egp.OPERATING_STATUS_CD
		, egp.LAT_DEG
		, egp.LONG_DEG
		, egp.RELEASE_HEIGHT
		, egp.BASE_ELEVATION
		, egp.HEIGHT
		, egp.DIAMETER
		, egp.EXIT_GAS_VELOCITY
		, egp.EXIT_GAS_TEMP_MAX
		, egp.EXIT_GAS_TEMP_AVG
		, egp.EXIT_GAS_FLOW_MAX
		, egp.EXIT_GAS_FLOW_AVG
		, rpa.RELEASE_POINT_APPORTIONMENT 
	FROM PIMA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep
	CROSS APPLY PIMA_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa 
	CROSS APPLY PIMA_IMPACT_SHARE.dbo.FP_EGRESS_POINT egp 
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = fep.EMU_ID
	INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
	WHERE 
		egp.FPNODE_ID = rpa.TO_FPNODE_ID 
		AND fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'PINAL' AS PARTNER_ID
		, fep.EMU_ID
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, egp.FPNODE_ID AS RELEASEPOINT_FPNODE_ID
		, egp.EGRESS_POINT_TYPE_CD
		, egp.DAPC_DSC
		, egp.REGULATED_USER_DSC
		, egp.OPERATING_STATUS_CD
		, egp.LAT_DEG
		, egp.LONG_DEG
		, egp.RELEASE_HEIGHT
		, egp.BASE_ELEVATION
		, egp.HEIGHT
		, egp.DIAMETER
		, egp.EXIT_GAS_VELOCITY
		, egp.EXIT_GAS_TEMP_MAX
		, egp.EXIT_GAS_TEMP_AVG
		, egp.EXIT_GAS_FLOW_MAX
		, egp.EXIT_GAS_FLOW_AVG
		, rpa.RELEASE_POINT_APPORTIONMENT 
	FROM PINAL_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep
	CROSS APPLY PINAL_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa 
	CROSS APPLY PINAL_IMPACT_SHARE.dbo.FP_EGRESS_POINT egp 
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = fep.EMU_ID
	INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
	WHERE 
		egp.FPNODE_ID = rpa.TO_FPNODE_ID 
		AND fp.VERSION_ID = -1

	UNION ALL

	SELECT 
		N'FMYN' AS PARTNER_ID
		, fep.EMU_ID
		, fep.FPNODE_ID AS PROCESS_FPNODE_ID
		, egp.FPNODE_ID AS RELEASEPOINT_FPNODE_ID
		, egp.EGRESS_POINT_TYPE_CD
		, egp.DAPC_DSC
		, egp.REGULATED_USER_DSC
		, egp.OPERATING_STATUS_CD
		, egp.LAT_DEG
		, egp.LONG_DEG
		, egp.RELEASE_HEIGHT
		, egp.BASE_ELEVATION
		, egp.HEIGHT
		, egp.DIAMETER
		, egp.EXIT_GAS_VELOCITY
		, egp.EXIT_GAS_TEMP_MAX
		, egp.EXIT_GAS_TEMP_AVG
		, egp.EXIT_GAS_FLOW_MAX
		, egp.EXIT_GAS_FLOW_AVG
		, rpa.RELEASE_POINT_APPORTIONMENT 
	FROM FMYN_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep
	CROSS APPLY FMYN_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa 
	CROSS APPLY FMYN_IMPACT_SHARE.dbo.FP_EGRESS_POINT egp 
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.EMU_ID = fep.EMU_ID
	INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = feu.FP_ID
	WHERE 
		egp.FPNODE_ID = rpa.TO_FPNODE_ID 
		AND fp.VERSION_ID = -1
GO
-- view dbo.RELEASE_POINT end

-- view dbo.RELEASE_POINT_APPORTIONMENT start
DROP VIEW IF EXISTS [dbo].[RELEASE_POINT_APPORTIONMENT]
GO

CREATE VIEW [dbo].[RELEASE_POINT_APPORTIONMENT]
AS
	SELECT
		N'GRIC' AS PARTNER_ID
		, feu.FP_ID
		, fp.VERSION_ID
		, fp.FACILITY_ID
		, feu.EMU_ID
		, feu.CORR_EPA_EMU_ID
		, feu.EPA_EMU_ID
		, fep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
		, fep.PROCESS_ID
		, fep.SCC_ID
		, rpa.TO_FPNODE_ID AS RELEASE_POINT_FPNODE_ID
		, feg.RELEASE_POINT_ID
		, rpa.RELEASE_POINT_APPORTIONMENT
		FROM GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp
		INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.FP_ID = fp.FP_ID
		LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID
		OUTER APPLY GRIC_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa
		LEFT OUTER JOIN GRIC_IMPACT_SHARE.dbo.FP_EGRESS_POINT feg ON feg.FPNODE_ID = rpa.TO_FPNODE_ID

		UNION ALL

		SELECT
			N'MARICOPA' AS PARTNER_ID
			, feu.FP_ID
			, fp.VERSION_ID
			, fp.FACILITY_ID
			, feu.EMU_ID
			, feu.CORR_EPA_EMU_ID
			, feu.EPA_EMU_ID
			, fep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, fep.PROCESS_ID
			, fep.SCC_ID
			, rpa.TO_FPNODE_ID AS RELEASE_POINT_FPNODE_ID
			, feg.RELEASE_POINT_ID
			, rpa.RELEASE_POINT_APPORTIONMENT
			FROM MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.FP_ID = fp.FP_ID
			LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID
			OUTER APPLY MARICOPA_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa
			LEFT OUTER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EGRESS_POINT feg ON feg.FPNODE_ID = rpa.TO_FPNODE_ID

		UNION ALL

		SELECT
			N'PIMA' AS PARTNER_ID
			, feu.FP_ID
			, fp.VERSION_ID
			, fp.FACILITY_ID
			, feu.EMU_ID
			, feu.CORR_EPA_EMU_ID
			, feu.EPA_EMU_ID
			, fep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, fep.PROCESS_ID
			, fep.SCC_ID
			, rpa.TO_FPNODE_ID AS RELEASE_POINT_FPNODE_ID
			, feg.RELEASE_POINT_ID
			, rpa.RELEASE_POINT_APPORTIONMENT
			FROM PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp
			INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.FP_ID = fp.FP_ID
			LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID
			OUTER APPLY PIMA_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa
			LEFT OUTER JOIN PIMA_IMPACT_SHARE.dbo.FP_EGRESS_POINT feg ON feg.FPNODE_ID = rpa.TO_FPNODE_ID

		UNION ALL

		SELECT
			N'PINAL' AS PARTNER_ID
			, feu.FP_ID
			, fp.VERSION_ID
			, fp.FACILITY_ID
			, feu.EMU_ID
			, feu.CORR_EPA_EMU_ID
			, feu.EPA_EMU_ID
			, fep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, fep.PROCESS_ID
			, fep.SCC_ID
			, rpa.TO_FPNODE_ID AS RELEASE_POINT_FPNODE_ID
			, feg.RELEASE_POINT_ID
			, rpa.RELEASE_POINT_APPORTIONMENT
			FROM PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp
			INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.FP_ID = fp.FP_ID
			LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID
			OUTER APPLY PINAL_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa
			LEFT OUTER JOIN PINAL_IMPACT_SHARE.dbo.FP_EGRESS_POINT feg ON feg.FPNODE_ID = rpa.TO_FPNODE_ID

		UNION ALL

		SELECT
			N'FMYN' AS PARTNER_ID
			, feu.FP_ID
			, fp.VERSION_ID
			, fp.FACILITY_ID
			, feu.EMU_ID
			, feu.CORR_EPA_EMU_ID
			, feu.EPA_EMU_ID
			, fep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, fep.PROCESS_ID
			, fep.SCC_ID
			, rpa.TO_FPNODE_ID AS RELEASE_POINT_FPNODE_ID
			, feg.RELEASE_POINT_ID
			, rpa.RELEASE_POINT_APPORTIONMENT
			FROM FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp
			INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON feu.FP_ID = fp.FP_ID
			LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS fep ON fep.EMU_ID = feu.EMU_ID
			OUTER APPLY FMYN_IMPACT_SHARE.dbo.udf_GetReleasePointApportionment(fep.FPNODE_ID) rpa
			LEFT OUTER JOIN FMYN_IMPACT_SHARE.dbo.FP_EGRESS_POINT feg ON feg.FPNODE_ID = rpa.TO_FPNODE_ID
GO
-- view dbo.RELEASE_POINT_APPORTIONMENT end

-- view dbo.EGRESS_POINT start
DROP VIEW IF EXISTS [dbo].[FP_EGRESS_POINT]
GO

CREATE VIEW [dbo].[FP_EGRESS_POINT] AS
	SELECT N'GRIC' AS PARTNER_ID, * FROM GRIC_IMPACT_SHARE.dbo.FP_EGRESS_POINT
	UNION ALL
	SELECT N'MARICOPA' AS PARTNER_ID, * FROM MARICOPA_IMPACT_SHARE.dbo.FP_EGRESS_POINT
	UNION ALL
	SELECT N'PIMA' AS PARTNER_ID, * FROM PIMA_IMPACT_SHARE.dbo.FP_EGRESS_POINT
	UNION ALL
	SELECT N'PINAL' AS PARTNER_ID, * FROM PINAL_IMPACT_SHARE.dbo.FP_EGRESS_POINT
	UNION ALL
	SELECT N'FMYN' AS PARTNER_ID, * FROM FMYN_IMPACT_SHARE.dbo.FP_EGRESS_POINT
GO
-- view dbo.EGRESS_POINT end

-- view dbo.EMISSION_PERIOD start
DROP VIEW IF EXISTS [dbo].[EMISSION_PERIOD]
GO


CREATE VIEW [dbo].[EMISSION_PERIOD] AS 
	SELECT 
		N'GRIC' AS PARTNER_ID
		, r.FP_ID 
		, r.FACILITY_ID
		, r.FACILITY_NM
		, r.EMISSIONS_RPT_ID
		, r.EI_ID
		, r.REPORT_YEAR
		, r.RPT_RECEIVED_STATUS_CD
		, r.RPT_RECEIVED_STATUS_DSC
		, feu.EMU_ID
		, feu.EPA_EMU_ID
		, feu.EU_DESC
		, ep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
		, ep.PROCESS_ID
		, ep.SCC_ID
		, ep.EMISSION_PROCESS_DSC
		, rep.EMISSION_PERIOD_ID
		, rep.WINTER_THROUGHPUT_PCT
		, rep.SPRING_THROUGHPUT_PCT
		, rep.SUMMER_THROUGHPUT_PCT
		, rep.FALL_THROUGHPUT_PCT
		, rep.HOURS_PER_YEAR
		FROM (
			SELECT 
				ROW_NUMBER() OVER (PARTITION BY er.REPORT_YEAR, er.RPT_RECEIVED_STATUS_CD, fp.FACILITY_ID ORDER BY er.EMISSIONS_RPT_ID DESC) AS RN
				, er.FP_ID
				, er.REPORT_YEAR
				, er.EI_ID
				, er.EMISSIONS_RPT_ID
				, er.RPT_RECEIVED_STATUS_CD
				, fp.FACILITY_ID
				, fp.FACILITY_NM
				, rrsd.RPT_RECEIVED_STATUS_DSC
				FROM GRIC_IMPACT_SHARE.dbo.RP_EMISSIONS_RPT er
				INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = er.FP_ID
				INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_RPT_RECEIVED_STATUS_DEF rrsd ON rrsd.RPT_RECEIVED_STATUS_CD = er.RPT_RECEIVED_STATUS_CD
				WHERE er.RPT_RECEIVED_STATUS_CD = N'10aa'
		) r
		INNER JOIN GRIC_IMPACT_SHARE.dbo.RP_REPORT_EU reu ON reu.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
		INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON (feu.CORR_EPA_EMU_ID = reu.CORR_ID AND feu.FP_ID = r.FP_ID)
		INNER JOIN GRIC_IMPACT_SHARE.dbo.RP_REPORT_PERIOD_XREF rpx ON rpx.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
		INNER JOIN GRIC_IMPACT_SHARE.dbo.RP_EMISSION_PERIOD rep ON rep.EMISSION_PERIOD_ID = rpx.EMISSION_PERIOD_ID
		INNER JOIN GRIC_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS ep ON (ep.EMU_ID = feu.EMU_ID AND ep.SCC_ID = rep.SCC_ID AND feu.CORR_EPA_EMU_ID = rpx.CORR_ID)
		WHERE r.RN = 1 

		UNION ALL

		SELECT 
			N'MARICOPA' AS PARTNER_ID
			, r.FP_ID 
			, r.FACILITY_ID
			, r.FACILITY_NM
			, r.EMISSIONS_RPT_ID
			, r.EI_ID
			, r.REPORT_YEAR
			, r.RPT_RECEIVED_STATUS_CD
			, r.RPT_RECEIVED_STATUS_DSC
			, feu.EMU_ID
			, feu.EPA_EMU_ID
			, feu.EU_DESC
			, ep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, rep.EMISSION_PERIOD_ID
			, rep.WINTER_THROUGHPUT_PCT
			, rep.SPRING_THROUGHPUT_PCT
			, rep.SUMMER_THROUGHPUT_PCT
			, rep.FALL_THROUGHPUT_PCT
			, rep.HOURS_PER_YEAR
			FROM (
				SELECT 
					ROW_NUMBER() OVER (PARTITION BY er.REPORT_YEAR, er.RPT_RECEIVED_STATUS_CD, fp.FACILITY_ID ORDER BY er.EMISSIONS_RPT_ID DESC) AS RN
					, er.FP_ID
					, er.REPORT_YEAR
					, er.EI_ID
					, er.EMISSIONS_RPT_ID
					, er.RPT_RECEIVED_STATUS_CD
					, fp.FACILITY_ID
					, fp.FACILITY_NM
					, rrsd.RPT_RECEIVED_STATUS_DSC
					FROM MARICOPA_IMPACT_SHARE.dbo.RP_EMISSIONS_RPT er
					INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = er.FP_ID
					INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_RPT_RECEIVED_STATUS_DEF rrsd ON rrsd.RPT_RECEIVED_STATUS_CD = er.RPT_RECEIVED_STATUS_CD
					WHERE er.RPT_RECEIVED_STATUS_CD = N'10aa'
			) r
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.RP_REPORT_EU reu ON reu.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON (feu.CORR_EPA_EMU_ID = reu.CORR_ID AND feu.FP_ID = r.FP_ID)
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.RP_REPORT_PERIOD_XREF rpx ON rpx.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.RP_EMISSION_PERIOD rep ON rep.EMISSION_PERIOD_ID = rpx.EMISSION_PERIOD_ID
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS ep ON (ep.EMU_ID = feu.EMU_ID AND ep.SCC_ID = rep.SCC_ID AND feu.CORR_EPA_EMU_ID = rpx.CORR_ID)
			WHERE r.RN = 1 

		UNION ALL

		SELECT 
			N'PIMA' AS PARTNER_ID
			, r.FP_ID 
			, r.FACILITY_ID
			, r.FACILITY_NM
			, r.EMISSIONS_RPT_ID
			, r.EI_ID
			, r.REPORT_YEAR
			, r.RPT_RECEIVED_STATUS_CD
			, r.RPT_RECEIVED_STATUS_DSC
			, feu.EMU_ID
			, feu.EPA_EMU_ID
			, feu.EU_DESC
			, ep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, rep.EMISSION_PERIOD_ID
			, rep.WINTER_THROUGHPUT_PCT
			, rep.SPRING_THROUGHPUT_PCT
			, rep.SUMMER_THROUGHPUT_PCT
			, rep.FALL_THROUGHPUT_PCT
			, rep.HOURS_PER_YEAR
			FROM (
				SELECT 
					ROW_NUMBER() OVER (PARTITION BY er.REPORT_YEAR, er.RPT_RECEIVED_STATUS_CD, fp.FACILITY_ID ORDER BY er.EMISSIONS_RPT_ID DESC) AS RN
					, er.FP_ID
					, er.REPORT_YEAR
					, er.EI_ID
					, er.EMISSIONS_RPT_ID
					, er.RPT_RECEIVED_STATUS_CD
					, fp.FACILITY_ID
					, fp.FACILITY_NM
					, rrsd.RPT_RECEIVED_STATUS_DSC
					FROM PIMA_IMPACT_SHARE.dbo.RP_EMISSIONS_RPT er
					INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = er.FP_ID
					INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_RPT_RECEIVED_STATUS_DEF rrsd ON rrsd.RPT_RECEIVED_STATUS_CD = er.RPT_RECEIVED_STATUS_CD
					WHERE er.RPT_RECEIVED_STATUS_CD = N'10aa'
			) r
			INNER JOIN PIMA_IMPACT_SHARE.dbo.RP_REPORT_EU reu ON reu.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON (feu.CORR_EPA_EMU_ID = reu.CORR_ID AND feu.FP_ID = r.FP_ID)
			INNER JOIN PIMA_IMPACT_SHARE.dbo.RP_REPORT_PERIOD_XREF rpx ON rpx.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN PIMA_IMPACT_SHARE.dbo.RP_EMISSION_PERIOD rep ON rep.EMISSION_PERIOD_ID = rpx.EMISSION_PERIOD_ID
			INNER JOIN PIMA_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS ep ON (ep.EMU_ID = feu.EMU_ID AND ep.SCC_ID = rep.SCC_ID AND feu.CORR_EPA_EMU_ID = rpx.CORR_ID)
			WHERE r.RN = 1 

		UNION ALL

		SELECT 
			N'PINAL' AS PARTNER_ID
			, r.FP_ID 
			, r.FACILITY_ID
			, r.FACILITY_NM
			, r.EMISSIONS_RPT_ID
			, r.EI_ID
			, r.REPORT_YEAR
			, r.RPT_RECEIVED_STATUS_CD
			, r.RPT_RECEIVED_STATUS_DSC
			, feu.EMU_ID
			, feu.EPA_EMU_ID
			, feu.EU_DESC
			, ep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, rep.EMISSION_PERIOD_ID
			, rep.WINTER_THROUGHPUT_PCT
			, rep.SPRING_THROUGHPUT_PCT
			, rep.SUMMER_THROUGHPUT_PCT
			, rep.FALL_THROUGHPUT_PCT
			, rep.HOURS_PER_YEAR
			FROM (
				SELECT 
					ROW_NUMBER() OVER (PARTITION BY er.REPORT_YEAR, er.RPT_RECEIVED_STATUS_CD, fp.FACILITY_ID ORDER BY er.EMISSIONS_RPT_ID DESC) AS RN
					, er.FP_ID
					, er.REPORT_YEAR
					, er.EI_ID
					, er.EMISSIONS_RPT_ID
					, er.RPT_RECEIVED_STATUS_CD
					, fp.FACILITY_ID
					, fp.FACILITY_NM
					, rrsd.RPT_RECEIVED_STATUS_DSC
					FROM PINAL_IMPACT_SHARE.dbo.RP_EMISSIONS_RPT er
					INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = er.FP_ID
					INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_RPT_RECEIVED_STATUS_DEF rrsd ON rrsd.RPT_RECEIVED_STATUS_CD = er.RPT_RECEIVED_STATUS_CD
					WHERE er.RPT_RECEIVED_STATUS_CD = N'10aa'
			) r
			INNER JOIN PINAL_IMPACT_SHARE.dbo.RP_REPORT_EU reu ON reu.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON (feu.CORR_EPA_EMU_ID = reu.CORR_ID AND feu.FP_ID = r.FP_ID)
			INNER JOIN PINAL_IMPACT_SHARE.dbo.RP_REPORT_PERIOD_XREF rpx ON rpx.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN PINAL_IMPACT_SHARE.dbo.RP_EMISSION_PERIOD rep ON rep.EMISSION_PERIOD_ID = rpx.EMISSION_PERIOD_ID
			INNER JOIN PINAL_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS ep ON (ep.EMU_ID = feu.EMU_ID AND ep.SCC_ID = rep.SCC_ID AND feu.CORR_EPA_EMU_ID = rpx.CORR_ID)
			WHERE r.RN = 1 

		UNION ALL

		SELECT 
			N'FMYN' AS PARTNER_ID
			, r.FP_ID 
			, r.FACILITY_ID
			, r.FACILITY_NM
			, r.EMISSIONS_RPT_ID
			, r.EI_ID
			, r.REPORT_YEAR
			, r.RPT_RECEIVED_STATUS_CD
			, r.RPT_RECEIVED_STATUS_DSC
			, feu.EMU_ID
			, feu.EPA_EMU_ID
			, feu.EU_DESC
			, ep.FPNODE_ID AS EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, rep.EMISSION_PERIOD_ID
			, rep.WINTER_THROUGHPUT_PCT
			, rep.SPRING_THROUGHPUT_PCT
			, rep.SUMMER_THROUGHPUT_PCT
			, rep.FALL_THROUGHPUT_PCT
			, rep.HOURS_PER_YEAR
			FROM (
				SELECT 
					ROW_NUMBER() OVER (PARTITION BY er.REPORT_YEAR, er.RPT_RECEIVED_STATUS_CD, fp.FACILITY_ID ORDER BY er.EMISSIONS_RPT_ID DESC) AS RN
					, er.FP_ID
					, er.REPORT_YEAR
					, er.EI_ID
					, er.EMISSIONS_RPT_ID
					, er.RPT_RECEIVED_STATUS_CD
					, fp.FACILITY_ID
					, fp.FACILITY_NM
					, rrsd.RPT_RECEIVED_STATUS_DSC
					FROM FMYN_IMPACT_SHARE.dbo.RP_EMISSIONS_RPT er
					INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_FACILITY fp ON fp.FP_ID = er.FP_ID
					INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_RPT_RECEIVED_STATUS_DEF rrsd ON rrsd.RPT_RECEIVED_STATUS_CD = er.RPT_RECEIVED_STATUS_CD
					WHERE er.RPT_RECEIVED_STATUS_CD = N'10aa'
			) r
			INNER JOIN FMYN_IMPACT_SHARE.dbo.RP_REPORT_EU reu ON reu.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSIONS_UNIT feu ON (feu.CORR_EPA_EMU_ID = reu.CORR_ID AND feu.FP_ID = r.FP_ID)
			INNER JOIN FMYN_IMPACT_SHARE.dbo.RP_REPORT_PERIOD_XREF rpx ON rpx.EMISSIONS_RPT_ID = r.EMISSIONS_RPT_ID
			INNER JOIN FMYN_IMPACT_SHARE.dbo.RP_EMISSION_PERIOD rep ON rep.EMISSION_PERIOD_ID = rpx.EMISSION_PERIOD_ID
			INNER JOIN FMYN_IMPACT_SHARE.dbo.FP_EMISSION_PROCESS ep ON (ep.EMU_ID = feu.EMU_ID AND ep.SCC_ID = rep.SCC_ID AND feu.CORR_EPA_EMU_ID = rpx.CORR_ID)
			WHERE r.RN = 1 
GO
-- view dbo.EMISSION_PERIOD end

-- view dbo.EMISSIONS start
DROP VIEW IF EXISTS [dbo].[EMISSIONS]
GO

CREATE VIEW [dbo].[EMISSIONS] AS
	SELECT 
		ep.PARTNER_ID
		, ep.FP_ID
		, ep.FACILITY_ID
		, ep.FACILITY_NM
		, ep.EMISSIONS_RPT_ID
		, ep.REPORT_YEAR
		, ep.EMU_ID
		, ep.EPA_EMU_ID
		, ep.EU_DESC
		, ep.EMISSION_PROCESS_FPNODE_ID
		, ep.PROCESS_ID
		, ep.SCC_ID
		, ep.EMISSION_PROCESS_DSC
		, ep.EMISSION_PERIOD_ID
		, re.POLLUTANT_CD
		, pd.POLLUTANT_DSC
		, re.EMISSION_CALC_METHOD_CD
		, ecmd.EMISSION_CALC_METHOD_DSC
		, re.FACTOR_NUMERIC_VALUE
		, CASE re.EMISSION_UNIT_NUMERATOR
			WHEN 'LB' THEN
					CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
			ELSE
				CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) AS DECIMAL (18, 10))
		END AS FUGITIVE_EMISSIONS
		, CASE re.EMISSION_UNIT_NUMERATOR
			WHEN 'LB' THEN
					CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
			ELSE
				CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT)AS DECIMAL (18, 10))
		END AS STACK_EMISSIONS
		, re.EXPLANATION 
		FROM IMPACT_SHARE.dbo.EMISSION_PERIOD ep
		INNER JOIN GRIC_IMPACT_SHARE.dbo.RP_EMISSIONS re ON (re.EMISSION_PERIOD_ID = ep.EMISSION_PERIOD_ID AND ep.PARTNER_ID = N'GRIC')
		INNER JOIN GRIC_IMPACT_SHARE.dbo.CM_POLLUTANT_DEF pd ON pd.POLLUTANT_CD = re.POLLUTANT_CD
		INNER JOIN GRIC_IMPACT_SHARE.dbo.RP_EMISSION_CALC_METHOD_DEF ecmd ON ecmd.EMISSION_CALC_METHOD_CD = re.EMISSION_CALC_METHOD_CD

		UNION ALL

		SELECT 
			ep.PARTNER_ID
			, ep.FP_ID
			, ep.FACILITY_ID
			, ep.FACILITY_NM
			, ep.EMISSIONS_RPT_ID
			, ep.REPORT_YEAR
			, ep.EMU_ID
			, ep.EPA_EMU_ID
			, ep.EU_DESC
			, ep.EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, ep.EMISSION_PERIOD_ID
			, re.POLLUTANT_CD
			, pd.POLLUTANT_DSC
			, re.EMISSION_CALC_METHOD_CD
			, ecmd.EMISSION_CALC_METHOD_DSC
			, re.FACTOR_NUMERIC_VALUE
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) AS DECIMAL (18, 10))
			END AS FUGITIVE_EMISSIONS
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT)AS DECIMAL (18, 10))
			END AS STACK_EMISSIONS
			, re.EXPLANATION 
			FROM IMPACT_SHARE.dbo.EMISSION_PERIOD ep
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.RP_EMISSIONS re ON (re.EMISSION_PERIOD_ID = ep.EMISSION_PERIOD_ID AND ep.PARTNER_ID = N'MARICOPA')
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.CM_POLLUTANT_DEF pd ON pd.POLLUTANT_CD = re.POLLUTANT_CD
			INNER JOIN MARICOPA_IMPACT_SHARE.dbo.RP_EMISSION_CALC_METHOD_DEF ecmd ON ecmd.EMISSION_CALC_METHOD_CD = re.EMISSION_CALC_METHOD_CD

		UNION ALL

		SELECT 
			ep.PARTNER_ID
			, ep.FP_ID
			, ep.FACILITY_ID
			, ep.FACILITY_NM
			, ep.EMISSIONS_RPT_ID
			, ep.REPORT_YEAR
			, ep.EMU_ID
			, ep.EPA_EMU_ID
			, ep.EU_DESC
			, ep.EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, ep.EMISSION_PERIOD_ID
			, re.POLLUTANT_CD
			, pd.POLLUTANT_DSC
			, re.EMISSION_CALC_METHOD_CD
			, ecmd.EMISSION_CALC_METHOD_DSC
			, re.FACTOR_NUMERIC_VALUE
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) AS DECIMAL (18, 10))
			END AS FUGITIVE_EMISSIONS
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT)AS DECIMAL (18, 10))
			END AS STACK_EMISSIONS
			, re.EXPLANATION 
			FROM IMPACT_SHARE.dbo.EMISSION_PERIOD ep
			INNER JOIN PIMA_IMPACT_SHARE.dbo.RP_EMISSIONS re ON (re.EMISSION_PERIOD_ID = ep.EMISSION_PERIOD_ID AND ep.PARTNER_ID = N'PIMA')
			INNER JOIN PIMA_IMPACT_SHARE.dbo.CM_POLLUTANT_DEF pd ON pd.POLLUTANT_CD = re.POLLUTANT_CD
			INNER JOIN PIMA_IMPACT_SHARE.dbo.RP_EMISSION_CALC_METHOD_DEF ecmd ON ecmd.EMISSION_CALC_METHOD_CD = re.EMISSION_CALC_METHOD_CD

		UNION ALL

		SELECT 
			ep.PARTNER_ID
			, ep.FP_ID
			, ep.FACILITY_ID
			, ep.FACILITY_NM
			, ep.EMISSIONS_RPT_ID
			, ep.REPORT_YEAR
			, ep.EMU_ID
			, ep.EPA_EMU_ID
			, ep.EU_DESC
			, ep.EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, ep.EMISSION_PERIOD_ID
			, re.POLLUTANT_CD
			, pd.POLLUTANT_DSC
			, re.EMISSION_CALC_METHOD_CD
			, ecmd.EMISSION_CALC_METHOD_DSC
			, re.FACTOR_NUMERIC_VALUE
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) AS DECIMAL (18, 10))
			END AS FUGITIVE_EMISSIONS
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT)AS DECIMAL (18, 10))
			END AS STACK_EMISSIONS
			, re.EXPLANATION 
			FROM IMPACT_SHARE.dbo.EMISSION_PERIOD ep
			INNER JOIN PINAL_IMPACT_SHARE.dbo.RP_EMISSIONS re ON (re.EMISSION_PERIOD_ID = ep.EMISSION_PERIOD_ID AND ep.PARTNER_ID = N'PINAL')
			INNER JOIN PINAL_IMPACT_SHARE.dbo.CM_POLLUTANT_DEF pd ON pd.POLLUTANT_CD = re.POLLUTANT_CD
			INNER JOIN PINAL_IMPACT_SHARE.dbo.RP_EMISSION_CALC_METHOD_DEF ecmd ON ecmd.EMISSION_CALC_METHOD_CD = re.EMISSION_CALC_METHOD_CD

		UNION ALL

		SELECT 
			ep.PARTNER_ID
			, ep.FP_ID
			, ep.FACILITY_ID
			, ep.FACILITY_NM
			, ep.EMISSIONS_RPT_ID
			, ep.REPORT_YEAR
			, ep.EMU_ID
			, ep.EPA_EMU_ID
			, ep.EU_DESC
			, ep.EMISSION_PROCESS_FPNODE_ID
			, ep.PROCESS_ID
			, ep.SCC_ID
			, ep.EMISSION_PROCESS_DSC
			, ep.EMISSION_PERIOD_ID
			, re.POLLUTANT_CD
			, pd.POLLUTANT_DSC
			, re.EMISSION_CALC_METHOD_CD
			, ecmd.EMISSION_CALC_METHOD_DSC
			, re.FACTOR_NUMERIC_VALUE
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.FUGITIVE_EMISSIONS, ',', '') AS FLOAT) AS DECIMAL (18, 10))
			END AS FUGITIVE_EMISSIONS
			, CASE re.EMISSION_UNIT_NUMERATOR
				WHEN 'LB' THEN
						CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT) * 0.0005 AS DECIMAL (18, 10))
				ELSE
					CAST(CAST(REPLACE(re.STACK_EMISSIONS, ',', '') AS FLOAT)AS DECIMAL (18, 10))
			END AS STACK_EMISSIONS
			, re.EXPLANATION 
			FROM IMPACT_SHARE.dbo.EMISSION_PERIOD ep
			INNER JOIN FMYN_IMPACT_SHARE.dbo.RP_EMISSIONS re ON (re.EMISSION_PERIOD_ID = ep.EMISSION_PERIOD_ID AND ep.PARTNER_ID = N'FMYN')
			INNER JOIN FMYN_IMPACT_SHARE.dbo.CM_POLLUTANT_DEF pd ON pd.POLLUTANT_CD = re.POLLUTANT_CD
			INNER JOIN FMYN_IMPACT_SHARE.dbo.RP_EMISSION_CALC_METHOD_DEF ecmd ON ecmd.EMISSION_CALC_METHOD_CD = re.EMISSION_CALC_METHOD_CD
GO
-- view dbo.EMISSIONS end

-- create stored procedures

-- stored procedure dbo.SearchFacilitiesByAreaAndPollutant start
DROP PROCEDURE IF EXISTS dbo.SearchFacilitiesByAreaAndPollutant
GO

CREATE PROCEDURE dbo.SearchFacilitiesByAreaAndPollutant
	@latitude AS NUMERIC(11,8),
	@longitude AS NUMERIC(11,8),
	@radius AS INT,
	@pollutant AS VARCHAR(256)
	
	AS

	DECLARE @geo geography = GEOGRAPHY::STGeomFromText('POINT('+ convert(nvarchar(20), @longitude)+' '+ convert( nvarchar(20), @latitude)+')', 4269) 

	SELECT DISTINCT 
	f.PARTNER_ID, 
	f.FP_ID, 
	f.FACILITY_ID, 
	f.FACILITY_NM, 
	c.COMPANY_ID, 
	c.NAME AS COMPANY_NAME, 
	f.PERMIT_CLASSIFICATION_DSC, 
	f.OPERATING_STATUS_DSC, 
	f.LATITUDE, 
	f.LONGITUDE 
	FROM dbo.EMISSIONS e
	INNER JOIN dbo.FACILITY f ON e.PARTNER_ID = f.PARTNER_ID AND e.FACILITY_ID = F.FACILITY_ID 
	INNER JOIN dbo.COMPANY C ON c.COMPANY_ID = f.COMPANY_ID AND c.PARTNER_ID = f.PARTNER_ID 
	WHERE e.POLLUTANT_DSC LIKE '%' + @pollutant + '%' 
	AND GEOGRAPHY::STGeomFromText('POINT('+ convert(nvarchar(20),LONGITUDE)+' '+ convert( nvarchar(20),LATITUDE)+')', 4269).STDistance(@geo) <= @radius * 1609.34 /*convert miles to meters*/
GO
-- stored procedure dbo.SearchFacilitiesByAreaAndPollutant end

-- stored procedure dbo.ExtractDispersionModelingData start
DROP PROCEDURE IF EXISTS dbo.ExtractDispersionModelingData
GO

CREATE PROCEDURE dbo.ExtractDispersionModelingData
	@latitude NUMERIC(11,8),
	@longitude NUMERIC(11,8),
	@radius INT,
	@pollutant VARCHAR(256)

	AS

	DECLARE @geo geography = GEOGRAPHY::STGeomFromText('POINT('+ convert(nvarchar(20), @longitude)+' '+ convert( nvarchar(20), @latitude)+')', 4269) 

	SELECT * FROM
	(
		SELECT 
			fp.PARTNER_ID
			, fp.FACILITY_ID
			, fp.FACILITY_NM
			, fep.RELEASE_POINT_ID
			, fep.RELEASE_HEIGHT
			, CASE 
				WHEN fep.RELEASE_POINT_ID IS NULL THEN fp.LATITUDE 
				ELSE fep.LAT_DEG
			  END AS LAT_DEG
			, CASE 
				WHEN fep.RELEASE_POINT_ID IS NULL THEN fp.LONGITUDE 
				ELSE fep.LONG_DEG
			  END AS LONG_DEG
			, d.POLLUTANT_DSC
			, d.TOTAL_FUGITIVE_EMISSIONS
			, d.TOTAL_STACK_EMISSIONS
			FROM dbo.FP_FACILITY fp
			INNER JOIN
			(	
				SELECT 
						r.PARTNER_ID
						, r.FP_ID
						, r.REPORT_YEAR
						, r.POLLUTANT_DSC
						, r.RELEASE_POINT_FPNODE_ID  
						, SUM(r.FUGITIVE_EMISSIONS) AS TOTAL_FUGITIVE_EMISSIONS
						, SUM(r.STACK_EMISSIONS) AS TOTAL_STACK_EMISSIONS 
					FROM
					(	
						SELECT 
							e.PARTNER_ID
							, e.FP_ID
							, e.REPORT_YEAR
							, e.POLLUTANT_DSC
							, e.EMISSION_PROCESS_FPNODE_ID
							, rpa.RELEASE_POINT_FPNODE_ID
							, NULL AS FUGITIVE_EMISSIONS
							, (e.STACK_EMISSIONS * rpa.RELEASE_POINT_APPORTIONMENT) / 100 AS STACK_EMISSIONS
							, rpa.RELEASE_POINT_APPORTIONMENT
							FROM dbo.EMISSIONS e
							INNER JOIN dbo.RELEASE_POINT_APPORTIONMENT rpa ON (rpa.EMISSION_PROCESS_FPNODE_ID = e.EMISSION_PROCESS_FPNODE_ID 
								AND rpa.RELEASE_POINT_ID IS NOT NULL)
						UNION 
						SELECT 
							e.PARTNER_ID
							, e.FP_ID
							, e.REPORT_YEAR
							, e.POLLUTANT_DSC
							, e.EMISSION_PROCESS_FPNODE_ID
							, '000000' AS RELEASE_POINT_FPNODE_ID
							, e.FUGITIVE_EMISSIONS
							, NULL AS STACK_EMISSIONS
							, NULL RELEASE_POINT_APPORTIONMENT
							FROM dbo.EMISSIONS e
							INNER JOIN dbo.RELEASE_POINT_APPORTIONMENT rpa ON rpa.EMISSION_PROCESS_FPNODE_ID = e.EMISSION_PROCESS_FPNODE_ID
						) r GROUP BY r.PARTNER_ID, r.FP_ID, r.REPORT_YEAR, r.POLLUTANT_DSC, r.RELEASE_POINT_FPNODE_ID 
				) d ON d.PARTNER_ID = fp.PARTNER_ID AND d.FP_ID = fp.FP_ID
				LEFT OUTER JOIN dbo.FP_EGRESS_POINT fep ON fep.FPNODE_ID = d.RELEASE_POINT_FPNODE_ID
				) res
			WHERE res.POLLUTANT_DSC LIKE '%' + @pollutant + '%' 
			AND GEOGRAPHY::STGeomFromText('POINT('+ convert(nvarchar(20),res.LONG_DEG)+' '+ convert( nvarchar(20),res.LAT_DEG)+')', 4269).STDistance(@geo) <= @radius * 1609.34 /*convert miles to meters*/
GO
-- stored procedure dbo.ExtractDispersionModelingData end