<%@ page session="false" contentType="text/html;charset=windows-1252"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://myfaces.apache.org/tomahawk" prefix="t"%>
<%@ taglib uri="http://xmlns.oracle.com/adf/faces" prefix="af"%>
<%@ taglib uri="http://xmlns.oracle.com/adf/faces/html" prefix="afh"%>


<af:panelBox background="light" width="82%">

	<af:panelForm rows="3" maxColumns="3">
		<af:inputText label="Facility ID:" readOnly="True"
			value="#{reportProfile.facility.facilityId}" />
		<af:inputText label="Facility Name:" readOnly="True"
			value="#{reportProfile.facility.name}" />
		<af:inputText label="Content Type:" readOnly="True"
			value="#{facilityReference.contentTypeDefs.itemDesc[(empty reportProfile.report.contentTypeCd ? '' : reportProfile.report.contentTypeCd)]}" />
		<af:inputText label="Emissions Inventory ID:" readOnly="True"
			value="#{reportProfile.report.emissionsInventoryId}" />
		<af:inputText label="#{reportProfile.report.submitLabel}" id="reportSubmitDate"
			readOnly="true" value="#{reportProfile.report.submitValue}"
			rendered="#{!reportProfile.publicApp}"/>
		<af:inputText
			label="#{reportProfile.doRptCompare?'Compare Reports':'Reporting Year:'}"
			shortDesc="The year the emissions inventory covers" readOnly="true"
			value="#{reportProfile.report.reportYear}" />
		<af:selectInputDate label="Approved Date:" id="reportApproveDate"
			readOnly="true" rendered="#{!reportProfile.report.submittedCode && reportProfile.report.approved}"
			value="#{reportProfile.report.rptApprovedStatusDate}"/>
		<af:selectInputDate label="Completed Date:" id="reportHandledDate"
			readOnly="true" rendered="#{!reportProfile.report.submittedCode && !reportProfile.report.approved}"
			value="#{reportProfile.report.rptApprovedStatusDate}"/>
		<af:switcher defaultFacet="single"
			facetName="#{reportProfile.doRptCompare? 'compare' : 'single'}">
			<f:facet name="single">
					<af:inputText label="Reporting State:"
						shortDesc="State of Emissions Inventory (e.g., submitted, approved)"
						readOnly="True"
						value="#{facilityReference.reportReceivedStatusDefs.itemDesc[(empty reportProfile.report.rptReceivedStatusCd ? '' : reportProfile.report.rptReceivedStatusCd)]}" />
			</f:facet>
			<f:facet name="compare">
				<af:panelGroup>
					<af:inputText label="Compare Reports"
						shortDesc="The year the emissions inventory covers" readOnly="True"
						value="#{reportProfile.report.reportYear}:#{reportProfile.compareReport.reportYear}" />
					<af:inputText label="Reporting State:"
						shortDesc="State of Emissions Inventory (e.g., submitted, approved)"
						readOnly="True"
						value="#{facilityReference.reportReceivedStatusDefs.itemDesc[(empty reportProfile.report.rptReceivedStatusCd ? '' : reportProfile.report.rptReceivedStatusCd)]}:#{facilityReference.reportReceivedStatusDefs.itemDesc[(empty reportProfile.compareReport.rptReceivedStatusCd ? '' : reportProfile.compareReport.rptReceivedStatusCd)]}" />
				</af:panelGroup>
			</f:facet>
		</af:switcher>
		<af:inputText
			label="Generated From Imported File:" readOnly="true"
			value="#{reportProfile.report.autoGenerated ? 'Yes' : 'No'}" />
	</af:panelForm>

	
</af:panelBox>

